package com.pinganzhiyuan.model;

public class Channel {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column channel.id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column channel.name
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column channel.channel_name
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private String channelName;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column channel.id
     * @return  the value of channel.id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column channel.id
     * @param id  the value for channel.id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column channel.name
     * @return  the value of channel.name
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column channel.name
     * @param name  the value for channel.name
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column channel.channel_name
     * @return  the value of channel.channel_name
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column channel.channel_name
     * @param channelName  the value for channel.channel_name
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }
}