package com.pinganzhiyuan.model;

import java.util.Date;

public class ClientVersion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.id
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.name
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.logo_url
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private String logoUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.version_name
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private String versionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.version_code
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private Integer versionCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.change_log
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private String changeLog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.is_forced
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private Boolean isForced;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.download_url
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private String downloadUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.is_published
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private Boolean isPublished;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.platform_id
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private Byte platformId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.package_name
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private String packageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.channel_id
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private Long channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.mask_switch
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private Boolean maskSwitch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client_version.publish_time
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	private Date publishTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.id
	 * @return  the value of client_version.id
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.id
	 * @param id  the value for client_version.id
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.name
	 * @return  the value of client_version.name
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.name
	 * @param name  the value for client_version.name
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.logo_url
	 * @return  the value of client_version.logo_url
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public String getLogoUrl() {
		return logoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.logo_url
	 * @param logoUrl  the value for client_version.logo_url
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setLogoUrl(String logoUrl) {
		this.logoUrl = logoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.version_name
	 * @return  the value of client_version.version_name
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public String getVersionName() {
		return versionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.version_name
	 * @param versionName  the value for client_version.version_name
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.version_code
	 * @return  the value of client_version.version_code
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public Integer getVersionCode() {
		return versionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.version_code
	 * @param versionCode  the value for client_version.version_code
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setVersionCode(Integer versionCode) {
		this.versionCode = versionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.change_log
	 * @return  the value of client_version.change_log
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public String getChangeLog() {
		return changeLog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.change_log
	 * @param changeLog  the value for client_version.change_log
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setChangeLog(String changeLog) {
		this.changeLog = changeLog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.is_forced
	 * @return  the value of client_version.is_forced
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public Boolean getIsForced() {
		return isForced;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.is_forced
	 * @param isForced  the value for client_version.is_forced
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setIsForced(Boolean isForced) {
		this.isForced = isForced;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.download_url
	 * @return  the value of client_version.download_url
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public String getDownloadUrl() {
		return downloadUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.download_url
	 * @param downloadUrl  the value for client_version.download_url
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setDownloadUrl(String downloadUrl) {
		this.downloadUrl = downloadUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.is_published
	 * @return  the value of client_version.is_published
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public Boolean getIsPublished() {
		return isPublished;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.is_published
	 * @param isPublished  the value for client_version.is_published
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setIsPublished(Boolean isPublished) {
		this.isPublished = isPublished;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.platform_id
	 * @return  the value of client_version.platform_id
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public Byte getPlatformId() {
		return platformId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.platform_id
	 * @param platformId  the value for client_version.platform_id
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setPlatformId(Byte platformId) {
		this.platformId = platformId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.package_name
	 * @return  the value of client_version.package_name
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public String getPackageName() {
		return packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.package_name
	 * @param packageName  the value for client_version.package_name
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.channel_id
	 * @return  the value of client_version.channel_id
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public Long getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.channel_id
	 * @param channelId  the value for client_version.channel_id
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setChannelId(Long channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.mask_switch
	 * @return  the value of client_version.mask_switch
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public Boolean getMaskSwitch() {
		return maskSwitch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.mask_switch
	 * @param maskSwitch  the value for client_version.mask_switch
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setMaskSwitch(Boolean maskSwitch) {
		this.maskSwitch = maskSwitch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client_version.publish_time
	 * @return  the value of client_version.publish_time
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public Date getPublishTime() {
		return publishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client_version.publish_time
	 * @param publishTime  the value for client_version.publish_time
	 * @mbg.generated  Fri Mar 02 16:38:19 CST 2018
	 */
	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}
	
	private String channelName;

	public String getChannelName() {
		return channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	@Override
	public String toString() {
		return "ClientVersion [id=" + id + ", name=" + name + ", logoUrl=" + logoUrl + ", versionName=" + versionName
				+ ", versionCode=" + versionCode + ", changeLog=" + changeLog + ", isForced=" + isForced
				+ ", downloadUrl=" + downloadUrl + ", isPublished=" + isPublished + ", platformId=" + platformId
				+ ", packageName=" + packageName + ", channelId=" + channelId + ", maskSwitch=" + maskSwitch
				+ ", publishTime=" + publishTime + ", channelName=" + channelName + "]";
	}

}