package com.pinganzhiyuan.model;

import java.util.Date;

public class Client {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column client.id
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column client.user_id
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private Long userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column client.name
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column client.identity_no
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private String identityNo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column client.residence_addr
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private String residenceAddr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column client.is_man
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private Boolean isMan;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column client.nation
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private String nation;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column client.birthday
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private Date birthday;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column client.identity_auth
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private String identityAuth;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column client.identity_expiration
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private Date identityExpiration;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column client.education
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private String education;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column client.guarantee
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private String guarantee;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column client.profession
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private String profession;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column client.id
     * @return  the value of client.id
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column client.id
     * @param id  the value for client.id
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column client.user_id
     * @return  the value of client.user_id
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column client.user_id
     * @param userId  the value for client.user_id
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column client.name
     * @return  the value of client.name
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column client.name
     * @param name  the value for client.name
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column client.identity_no
     * @return  the value of client.identity_no
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public String getIdentityNo() {
        return identityNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column client.identity_no
     * @param identityNo  the value for client.identity_no
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setIdentityNo(String identityNo) {
        this.identityNo = identityNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column client.residence_addr
     * @return  the value of client.residence_addr
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public String getResidenceAddr() {
        return residenceAddr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column client.residence_addr
     * @param residenceAddr  the value for client.residence_addr
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setResidenceAddr(String residenceAddr) {
        this.residenceAddr = residenceAddr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column client.is_man
     * @return  the value of client.is_man
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public Boolean getIsMan() {
        return isMan;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column client.is_man
     * @param isMan  the value for client.is_man
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setIsMan(Boolean isMan) {
        this.isMan = isMan;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column client.nation
     * @return  the value of client.nation
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column client.nation
     * @param nation  the value for client.nation
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column client.birthday
     * @return  the value of client.birthday
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column client.birthday
     * @param birthday  the value for client.birthday
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column client.identity_auth
     * @return  the value of client.identity_auth
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public String getIdentityAuth() {
        return identityAuth;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column client.identity_auth
     * @param identityAuth  the value for client.identity_auth
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setIdentityAuth(String identityAuth) {
        this.identityAuth = identityAuth;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column client.identity_expiration
     * @return  the value of client.identity_expiration
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public Date getIdentityExpiration() {
        return identityExpiration;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column client.identity_expiration
     * @param identityExpiration  the value for client.identity_expiration
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setIdentityExpiration(Date identityExpiration) {
        this.identityExpiration = identityExpiration;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column client.education
     * @return  the value of client.education
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column client.education
     * @param education  the value for client.education
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column client.guarantee
     * @return  the value of client.guarantee
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public String getGuarantee() {
        return guarantee;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column client.guarantee
     * @param guarantee  the value for client.guarantee
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setGuarantee(String guarantee) {
        this.guarantee = guarantee;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column client.profession
     * @return  the value of client.profession
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column client.profession
     * @param profession  the value for client.profession
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setProfession(String profession) {
        this.profession = profession;
    }
}