package com.pinganzhiyuan.model;

import java.util.Date;

public class LogInStatisticDaily {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column statistic_log_in_daily.id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column statistic_log_in_daily.statistic_date
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Date statisticDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column statistic_log_in_daily.user_id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Long userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column statistic_log_in_daily.device_id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Long deviceId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column statistic_log_in_daily.log_in_time
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Date logInTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column statistic_log_in_daily.created_at
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column statistic_log_in_daily.id
     * @return  the value of statistic_log_in_daily.id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column statistic_log_in_daily.id
     * @param id  the value for statistic_log_in_daily.id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column statistic_log_in_daily.statistic_date
     * @return  the value of statistic_log_in_daily.statistic_date
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Date getStatisticDate() {
        return statisticDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column statistic_log_in_daily.statistic_date
     * @param statisticDate  the value for statistic_log_in_daily.statistic_date
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setStatisticDate(Date statisticDate) {
        this.statisticDate = statisticDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column statistic_log_in_daily.user_id
     * @return  the value of statistic_log_in_daily.user_id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column statistic_log_in_daily.user_id
     * @param userId  the value for statistic_log_in_daily.user_id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column statistic_log_in_daily.device_id
     * @return  the value of statistic_log_in_daily.device_id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column statistic_log_in_daily.device_id
     * @param deviceId  the value for statistic_log_in_daily.device_id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column statistic_log_in_daily.log_in_time
     * @return  the value of statistic_log_in_daily.log_in_time
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Date getLogInTime() {
        return logInTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column statistic_log_in_daily.log_in_time
     * @param logInTime  the value for statistic_log_in_daily.log_in_time
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setLogInTime(Date logInTime) {
        this.logInTime = logInTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column statistic_log_in_daily.created_at
     * @return  the value of statistic_log_in_daily.created_at
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column statistic_log_in_daily.created_at
     * @param createdAt  the value for statistic_log_in_daily.created_at
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}