package com.pinganzhiyuan.model;

public class MidNav {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mid_nav.id
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mid_nav.title
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mid_nav.subtitle
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    private String subtitle;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mid_nav.icon_url
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    private String iconUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mid_nav.url
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column mid_nav.product_id
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    private Long productId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mid_nav.id
     * @return  the value of mid_nav.id
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mid_nav.id
     * @param id  the value for mid_nav.id
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mid_nav.title
     * @return  the value of mid_nav.title
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mid_nav.title
     * @param title  the value for mid_nav.title
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mid_nav.subtitle
     * @return  the value of mid_nav.subtitle
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mid_nav.subtitle
     * @param subtitle  the value for mid_nav.subtitle
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mid_nav.icon_url
     * @return  the value of mid_nav.icon_url
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mid_nav.icon_url
     * @param iconUrl  the value for mid_nav.icon_url
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mid_nav.url
     * @return  the value of mid_nav.url
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mid_nav.url
     * @param url  the value for mid_nav.url
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column mid_nav.product_id
     * @return  the value of mid_nav.product_id
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column mid_nav.product_id
     * @param productId  the value for mid_nav.product_id
     * @mbg.generated  Mon Jan 29 11:35:42 CST 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }
}