package com.pinganzhiyuan.model;

public class Permission {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column permission.id
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column permission.name
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column permission.type
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    private String type;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column permission.url
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column permission.parent_id
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    private Long parentId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column permission.parent_ids
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    private String parentIds;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column permission.permission
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    private String permission;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column permission.is_enabled
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    private Boolean isEnabled;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column permission.id
     * @return  the value of permission.id
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column permission.id
     * @param id  the value for permission.id
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column permission.name
     * @return  the value of permission.name
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column permission.name
     * @param name  the value for permission.name
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column permission.type
     * @return  the value of permission.type
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column permission.type
     * @param type  the value for permission.type
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column permission.url
     * @return  the value of permission.url
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column permission.url
     * @param url  the value for permission.url
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column permission.parent_id
     * @return  the value of permission.parent_id
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column permission.parent_id
     * @param parentId  the value for permission.parent_id
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column permission.parent_ids
     * @return  the value of permission.parent_ids
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column permission.parent_ids
     * @param parentIds  the value for permission.parent_ids
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column permission.permission
     * @return  the value of permission.permission
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column permission.permission
     * @param permission  the value for permission.permission
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column permission.is_enabled
     * @return  the value of permission.is_enabled
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column permission.is_enabled
     * @param isEnabled  the value for permission.is_enabled
     * @mbg.generated  Mon Jan 15 11:33:27 CST 2018
     */
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }
}