package com.pinganzhiyuan.model;

public class ProductColumnMapping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_column_mapping.id
     *
     * @mbg.generated Mon Feb 05 09:45:08 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_column_mapping.column_key
     *
     * @mbg.generated Mon Feb 05 09:45:08 CST 2018
     */
    private String columnKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_column_mapping.product_id
     *
     * @mbg.generated Mon Feb 05 09:45:08 CST 2018
     */
    private Long productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_column_mapping.id
     *
     * @return the value of product_column_mapping.id
     *
     * @mbg.generated Mon Feb 05 09:45:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_column_mapping.id
     *
     * @param id the value for product_column_mapping.id
     *
     * @mbg.generated Mon Feb 05 09:45:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_column_mapping.column_key
     *
     * @return the value of product_column_mapping.column_key
     *
     * @mbg.generated Mon Feb 05 09:45:08 CST 2018
     */
    public String getColumnKey() {
        return columnKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_column_mapping.column_key
     *
     * @param columnKey the value for product_column_mapping.column_key
     *
     * @mbg.generated Mon Feb 05 09:45:08 CST 2018
     */
    public void setColumnKey(String columnKey) {
        this.columnKey = columnKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_column_mapping.product_id
     *
     * @return the value of product_column_mapping.product_id
     *
     * @mbg.generated Mon Feb 05 09:45:08 CST 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_column_mapping.product_id
     *
     * @param productId the value for product_column_mapping.product_id
     *
     * @mbg.generated Mon Feb 05 09:45:08 CST 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }
}