package com.pinganzhiyuan.model;

import java.util.Date;

public class ProductView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_view.id
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_view.statistic_date
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	private Date statisticDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_view.app_product_name
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	private String appProductName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_view.product_name
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_view.product_uv_count
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	private Integer productUvCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_view.product_pv_count
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	private Integer productPvCount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_view.id
	 * @return  the value of product_view.id
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_view.id
	 * @param id  the value for product_view.id
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_view.statistic_date
	 * @return  the value of product_view.statistic_date
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	public Date getStatisticDate() {
		return statisticDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_view.statistic_date
	 * @param statisticDate  the value for product_view.statistic_date
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	public void setStatisticDate(Date statisticDate) {
		this.statisticDate = statisticDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_view.app_product_name
	 * @return  the value of product_view.app_product_name
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	public String getAppProductName() {
		return appProductName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_view.app_product_name
	 * @param appProductName  the value for product_view.app_product_name
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	public void setAppProductName(String appProductName) {
		this.appProductName = appProductName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_view.product_name
	 * @return  the value of product_view.product_name
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_view.product_name
	 * @param productName  the value for product_view.product_name
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_view.product_uv_count
	 * @return  the value of product_view.product_uv_count
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	public Integer getProductUvCount() {
		return productUvCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_view.product_uv_count
	 * @param productUvCount  the value for product_view.product_uv_count
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	public void setProductUvCount(Integer productUvCount) {
		this.productUvCount = productUvCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_view.product_pv_count
	 * @return  the value of product_view.product_pv_count
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	public Integer getProductPvCount() {
		return productPvCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_view.product_pv_count
	 * @param productPvCount  the value for product_view.product_pv_count
	 * @mbg.generated  Thu Jan 11 10:59:20 CST 2018
	 */
	public void setProductPvCount(Integer productPvCount) {
		this.productPvCount = productPvCount;
	}
}