package com.pinganzhiyuan.model;

import java.util.Date;

public class ProductStatistic {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product_statistic.id
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product_statistic.product_id
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private Long productId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product_statistic.product_title
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private String productTitle;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product_statistic.record_date
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private Date recordDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product_statistic.visit_count
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private Integer visitCount;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product_statistic.visit_user_count
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private Integer visitUserCount;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product_statistic.average_stay_time
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    private Integer averageStayTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product_statistic.id
     * @return  the value of product_statistic.id
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product_statistic.id
     * @param id  the value for product_statistic.id
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product_statistic.product_id
     * @return  the value of product_statistic.product_id
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product_statistic.product_id
     * @param productId  the value for product_statistic.product_id
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product_statistic.product_title
     * @return  the value of product_statistic.product_title
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public String getProductTitle() {
        return productTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product_statistic.product_title
     * @param productTitle  the value for product_statistic.product_title
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setProductTitle(String productTitle) {
        this.productTitle = productTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product_statistic.record_date
     * @return  the value of product_statistic.record_date
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product_statistic.record_date
     * @param recordDate  the value for product_statistic.record_date
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product_statistic.visit_count
     * @return  the value of product_statistic.visit_count
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public Integer getVisitCount() {
        return visitCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product_statistic.visit_count
     * @param visitCount  the value for product_statistic.visit_count
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setVisitCount(Integer visitCount) {
        this.visitCount = visitCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product_statistic.visit_user_count
     * @return  the value of product_statistic.visit_user_count
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public Integer getVisitUserCount() {
        return visitUserCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product_statistic.visit_user_count
     * @param visitUserCount  the value for product_statistic.visit_user_count
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setVisitUserCount(Integer visitUserCount) {
        this.visitUserCount = visitUserCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product_statistic.average_stay_time
     * @return  the value of product_statistic.average_stay_time
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public Integer getAverageStayTime() {
        return averageStayTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product_statistic.average_stay_time
     * @param averageStayTime  the value for product_statistic.average_stay_time
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    public void setAverageStayTime(Integer averageStayTime) {
        this.averageStayTime = averageStayTime;
    }
}