package com.pinganzhiyuan.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andIsNewIsNull() {
            addCriterion("is_new is null");
            return (Criteria) this;
        }

        public Criteria andIsNewIsNotNull() {
            addCriterion("is_new is not null");
            return (Criteria) this;
        }

        public Criteria andIsNewEqualTo(Boolean value) {
            addCriterion("is_new =", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotEqualTo(Boolean value) {
            addCriterion("is_new <>", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewGreaterThan(Boolean value) {
            addCriterion("is_new >", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_new >=", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewLessThan(Boolean value) {
            addCriterion("is_new <", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewLessThanOrEqualTo(Boolean value) {
            addCriterion("is_new <=", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewIn(List<Boolean> values) {
            addCriterion("is_new in", values, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotIn(List<Boolean> values) {
            addCriterion("is_new not in", values, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewBetween(Boolean value1, Boolean value2) {
            addCriterion("is_new between", value1, value2, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_new not between", value1, value2, "isNew");
            return (Criteria) this;
        }

        public Criteria andFirstTagsIsNull() {
            addCriterion("first_tags is null");
            return (Criteria) this;
        }

        public Criteria andFirstTagsIsNotNull() {
            addCriterion("first_tags is not null");
            return (Criteria) this;
        }

        public Criteria andFirstTagsEqualTo(String value) {
            addCriterion("first_tags =", value, "firstTags");
            return (Criteria) this;
        }

        public Criteria andFirstTagsNotEqualTo(String value) {
            addCriterion("first_tags <>", value, "firstTags");
            return (Criteria) this;
        }

        public Criteria andFirstTagsGreaterThan(String value) {
            addCriterion("first_tags >", value, "firstTags");
            return (Criteria) this;
        }

        public Criteria andFirstTagsGreaterThanOrEqualTo(String value) {
            addCriterion("first_tags >=", value, "firstTags");
            return (Criteria) this;
        }

        public Criteria andFirstTagsLessThan(String value) {
            addCriterion("first_tags <", value, "firstTags");
            return (Criteria) this;
        }

        public Criteria andFirstTagsLessThanOrEqualTo(String value) {
            addCriterion("first_tags <=", value, "firstTags");
            return (Criteria) this;
        }

        public Criteria andFirstTagsLike(String value) {
            addCriterion("first_tags like", value, "firstTags");
            return (Criteria) this;
        }

        public Criteria andFirstTagsNotLike(String value) {
            addCriterion("first_tags not like", value, "firstTags");
            return (Criteria) this;
        }

        public Criteria andFirstTagsIn(List<String> values) {
            addCriterion("first_tags in", values, "firstTags");
            return (Criteria) this;
        }

        public Criteria andFirstTagsNotIn(List<String> values) {
            addCriterion("first_tags not in", values, "firstTags");
            return (Criteria) this;
        }

        public Criteria andFirstTagsBetween(String value1, String value2) {
            addCriterion("first_tags between", value1, value2, "firstTags");
            return (Criteria) this;
        }

        public Criteria andFirstTagsNotBetween(String value1, String value2) {
            addCriterion("first_tags not between", value1, value2, "firstTags");
            return (Criteria) this;
        }

        public Criteria andSecondTagsIsNull() {
            addCriterion("second_tags is null");
            return (Criteria) this;
        }

        public Criteria andSecondTagsIsNotNull() {
            addCriterion("second_tags is not null");
            return (Criteria) this;
        }

        public Criteria andSecondTagsEqualTo(String value) {
            addCriterion("second_tags =", value, "secondTags");
            return (Criteria) this;
        }

        public Criteria andSecondTagsNotEqualTo(String value) {
            addCriterion("second_tags <>", value, "secondTags");
            return (Criteria) this;
        }

        public Criteria andSecondTagsGreaterThan(String value) {
            addCriterion("second_tags >", value, "secondTags");
            return (Criteria) this;
        }

        public Criteria andSecondTagsGreaterThanOrEqualTo(String value) {
            addCriterion("second_tags >=", value, "secondTags");
            return (Criteria) this;
        }

        public Criteria andSecondTagsLessThan(String value) {
            addCriterion("second_tags <", value, "secondTags");
            return (Criteria) this;
        }

        public Criteria andSecondTagsLessThanOrEqualTo(String value) {
            addCriterion("second_tags <=", value, "secondTags");
            return (Criteria) this;
        }

        public Criteria andSecondTagsLike(String value) {
            addCriterion("second_tags like", value, "secondTags");
            return (Criteria) this;
        }

        public Criteria andSecondTagsNotLike(String value) {
            addCriterion("second_tags not like", value, "secondTags");
            return (Criteria) this;
        }

        public Criteria andSecondTagsIn(List<String> values) {
            addCriterion("second_tags in", values, "secondTags");
            return (Criteria) this;
        }

        public Criteria andSecondTagsNotIn(List<String> values) {
            addCriterion("second_tags not in", values, "secondTags");
            return (Criteria) this;
        }

        public Criteria andSecondTagsBetween(String value1, String value2) {
            addCriterion("second_tags between", value1, value2, "secondTags");
            return (Criteria) this;
        }

        public Criteria andSecondTagsNotBetween(String value1, String value2) {
            addCriterion("second_tags not between", value1, value2, "secondTags");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andIsPublishedIsNull() {
            addCriterion("is_published is null");
            return (Criteria) this;
        }

        public Criteria andIsPublishedIsNotNull() {
            addCriterion("is_published is not null");
            return (Criteria) this;
        }

        public Criteria andIsPublishedEqualTo(Integer value) {
            addCriterion("is_published =", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedNotEqualTo(Integer value) {
            addCriterion("is_published <>", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedGreaterThan(Integer value) {
            addCriterion("is_published >", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_published >=", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedLessThan(Integer value) {
            addCriterion("is_published <", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedLessThanOrEqualTo(Integer value) {
            addCriterion("is_published <=", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedIn(List<Integer> values) {
            addCriterion("is_published in", values, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedNotIn(List<Integer> values) {
            addCriterion("is_published not in", values, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedBetween(Integer value1, Integer value2) {
            addCriterion("is_published between", value1, value2, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_published not between", value1, value2, "isPublished");
            return (Criteria) this;
        }

        public Criteria andImgUrlIsNull() {
            addCriterion("img_url is null");
            return (Criteria) this;
        }

        public Criteria andImgUrlIsNotNull() {
            addCriterion("img_url is not null");
            return (Criteria) this;
        }

        public Criteria andImgUrlEqualTo(String value) {
            addCriterion("img_url =", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotEqualTo(String value) {
            addCriterion("img_url <>", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlGreaterThan(String value) {
            addCriterion("img_url >", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("img_url >=", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlLessThan(String value) {
            addCriterion("img_url <", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlLessThanOrEqualTo(String value) {
            addCriterion("img_url <=", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlLike(String value) {
            addCriterion("img_url like", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotLike(String value) {
            addCriterion("img_url not like", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlIn(List<String> values) {
            addCriterion("img_url in", values, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotIn(List<String> values) {
            addCriterion("img_url not in", values, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlBetween(String value1, String value2) {
            addCriterion("img_url between", value1, value2, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotBetween(String value1, String value2) {
            addCriterion("img_url not between", value1, value2, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Integer value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Integer value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Integer value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Integer value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Integer value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Integer> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Integer> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Integer value1, Integer value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andLightTitleIsNull() {
            addCriterion("light_title is null");
            return (Criteria) this;
        }

        public Criteria andLightTitleIsNotNull() {
            addCriterion("light_title is not null");
            return (Criteria) this;
        }

        public Criteria andLightTitleEqualTo(String value) {
            addCriterion("light_title =", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleNotEqualTo(String value) {
            addCriterion("light_title <>", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleGreaterThan(String value) {
            addCriterion("light_title >", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleGreaterThanOrEqualTo(String value) {
            addCriterion("light_title >=", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleLessThan(String value) {
            addCriterion("light_title <", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleLessThanOrEqualTo(String value) {
            addCriterion("light_title <=", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleLike(String value) {
            addCriterion("light_title like", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleNotLike(String value) {
            addCriterion("light_title not like", value, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleIn(List<String> values) {
            addCriterion("light_title in", values, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleNotIn(List<String> values) {
            addCriterion("light_title not in", values, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleBetween(String value1, String value2) {
            addCriterion("light_title between", value1, value2, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andLightTitleNotBetween(String value1, String value2) {
            addCriterion("light_title not between", value1, value2, "lightTitle");
            return (Criteria) this;
        }

        public Criteria andEduIsNull() {
            addCriterion("edu is null");
            return (Criteria) this;
        }

        public Criteria andEduIsNotNull() {
            addCriterion("edu is not null");
            return (Criteria) this;
        }

        public Criteria andEduEqualTo(String value) {
            addCriterion("edu =", value, "edu");
            return (Criteria) this;
        }

        public Criteria andEduNotEqualTo(String value) {
            addCriterion("edu <>", value, "edu");
            return (Criteria) this;
        }

        public Criteria andEduGreaterThan(String value) {
            addCriterion("edu >", value, "edu");
            return (Criteria) this;
        }

        public Criteria andEduGreaterThanOrEqualTo(String value) {
            addCriterion("edu >=", value, "edu");
            return (Criteria) this;
        }

        public Criteria andEduLessThan(String value) {
            addCriterion("edu <", value, "edu");
            return (Criteria) this;
        }

        public Criteria andEduLessThanOrEqualTo(String value) {
            addCriterion("edu <=", value, "edu");
            return (Criteria) this;
        }

        public Criteria andEduLike(String value) {
            addCriterion("edu like", value, "edu");
            return (Criteria) this;
        }

        public Criteria andEduNotLike(String value) {
            addCriterion("edu not like", value, "edu");
            return (Criteria) this;
        }

        public Criteria andEduIn(List<String> values) {
            addCriterion("edu in", values, "edu");
            return (Criteria) this;
        }

        public Criteria andEduNotIn(List<String> values) {
            addCriterion("edu not in", values, "edu");
            return (Criteria) this;
        }

        public Criteria andEduBetween(String value1, String value2) {
            addCriterion("edu between", value1, value2, "edu");
            return (Criteria) this;
        }

        public Criteria andEduNotBetween(String value1, String value2) {
            addCriterion("edu not between", value1, value2, "edu");
            return (Criteria) this;
        }

        public Criteria andMinAmountIsNull() {
            addCriterion("min_amount is null");
            return (Criteria) this;
        }

        public Criteria andMinAmountIsNotNull() {
            addCriterion("min_amount is not null");
            return (Criteria) this;
        }

        public Criteria andMinAmountEqualTo(Integer value) {
            addCriterion("min_amount =", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountNotEqualTo(Integer value) {
            addCriterion("min_amount <>", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountGreaterThan(Integer value) {
            addCriterion("min_amount >", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("min_amount >=", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountLessThan(Integer value) {
            addCriterion("min_amount <", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountLessThanOrEqualTo(Integer value) {
            addCriterion("min_amount <=", value, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountIn(List<Integer> values) {
            addCriterion("min_amount in", values, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountNotIn(List<Integer> values) {
            addCriterion("min_amount not in", values, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountBetween(Integer value1, Integer value2) {
            addCriterion("min_amount between", value1, value2, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMinAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("min_amount not between", value1, value2, "minAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountIsNull() {
            addCriterion("max_amount is null");
            return (Criteria) this;
        }

        public Criteria andMaxAmountIsNotNull() {
            addCriterion("max_amount is not null");
            return (Criteria) this;
        }

        public Criteria andMaxAmountEqualTo(Integer value) {
            addCriterion("max_amount =", value, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountNotEqualTo(Integer value) {
            addCriterion("max_amount <>", value, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountGreaterThan(Integer value) {
            addCriterion("max_amount >", value, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_amount >=", value, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountLessThan(Integer value) {
            addCriterion("max_amount <", value, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountLessThanOrEqualTo(Integer value) {
            addCriterion("max_amount <=", value, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountIn(List<Integer> values) {
            addCriterion("max_amount in", values, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountNotIn(List<Integer> values) {
            addCriterion("max_amount not in", values, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountBetween(Integer value1, Integer value2) {
            addCriterion("max_amount between", value1, value2, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMaxAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("max_amount not between", value1, value2, "maxAmount");
            return (Criteria) this;
        }

        public Criteria andMinTermIsNull() {
            addCriterion("min_term is null");
            return (Criteria) this;
        }

        public Criteria andMinTermIsNotNull() {
            addCriterion("min_term is not null");
            return (Criteria) this;
        }

        public Criteria andMinTermEqualTo(Integer value) {
            addCriterion("min_term =", value, "minTerm");
            return (Criteria) this;
        }

        public Criteria andMinTermNotEqualTo(Integer value) {
            addCriterion("min_term <>", value, "minTerm");
            return (Criteria) this;
        }

        public Criteria andMinTermGreaterThan(Integer value) {
            addCriterion("min_term >", value, "minTerm");
            return (Criteria) this;
        }

        public Criteria andMinTermGreaterThanOrEqualTo(Integer value) {
            addCriterion("min_term >=", value, "minTerm");
            return (Criteria) this;
        }

        public Criteria andMinTermLessThan(Integer value) {
            addCriterion("min_term <", value, "minTerm");
            return (Criteria) this;
        }

        public Criteria andMinTermLessThanOrEqualTo(Integer value) {
            addCriterion("min_term <=", value, "minTerm");
            return (Criteria) this;
        }

        public Criteria andMinTermIn(List<Integer> values) {
            addCriterion("min_term in", values, "minTerm");
            return (Criteria) this;
        }

        public Criteria andMinTermNotIn(List<Integer> values) {
            addCriterion("min_term not in", values, "minTerm");
            return (Criteria) this;
        }

        public Criteria andMinTermBetween(Integer value1, Integer value2) {
            addCriterion("min_term between", value1, value2, "minTerm");
            return (Criteria) this;
        }

        public Criteria andMinTermNotBetween(Integer value1, Integer value2) {
            addCriterion("min_term not between", value1, value2, "minTerm");
            return (Criteria) this;
        }

        public Criteria andMaxTermIsNull() {
            addCriterion("max_term is null");
            return (Criteria) this;
        }

        public Criteria andMaxTermIsNotNull() {
            addCriterion("max_term is not null");
            return (Criteria) this;
        }

        public Criteria andMaxTermEqualTo(Integer value) {
            addCriterion("max_term =", value, "maxTerm");
            return (Criteria) this;
        }

        public Criteria andMaxTermNotEqualTo(Integer value) {
            addCriterion("max_term <>", value, "maxTerm");
            return (Criteria) this;
        }

        public Criteria andMaxTermGreaterThan(Integer value) {
            addCriterion("max_term >", value, "maxTerm");
            return (Criteria) this;
        }

        public Criteria andMaxTermGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_term >=", value, "maxTerm");
            return (Criteria) this;
        }

        public Criteria andMaxTermLessThan(Integer value) {
            addCriterion("max_term <", value, "maxTerm");
            return (Criteria) this;
        }

        public Criteria andMaxTermLessThanOrEqualTo(Integer value) {
            addCriterion("max_term <=", value, "maxTerm");
            return (Criteria) this;
        }

        public Criteria andMaxTermIn(List<Integer> values) {
            addCriterion("max_term in", values, "maxTerm");
            return (Criteria) this;
        }

        public Criteria andMaxTermNotIn(List<Integer> values) {
            addCriterion("max_term not in", values, "maxTerm");
            return (Criteria) this;
        }

        public Criteria andMaxTermBetween(Integer value1, Integer value2) {
            addCriterion("max_term between", value1, value2, "maxTerm");
            return (Criteria) this;
        }

        public Criteria andMaxTermNotBetween(Integer value1, Integer value2) {
            addCriterion("max_term not between", value1, value2, "maxTerm");
            return (Criteria) this;
        }

        public Criteria andLowInterestIsNull() {
            addCriterion("low_interest is null");
            return (Criteria) this;
        }

        public Criteria andLowInterestIsNotNull() {
            addCriterion("low_interest is not null");
            return (Criteria) this;
        }

        public Criteria andLowInterestEqualTo(Double value) {
            addCriterion("low_interest =", value, "lowInterest");
            return (Criteria) this;
        }

        public Criteria andLowInterestNotEqualTo(Double value) {
            addCriterion("low_interest <>", value, "lowInterest");
            return (Criteria) this;
        }

        public Criteria andLowInterestGreaterThan(Double value) {
            addCriterion("low_interest >", value, "lowInterest");
            return (Criteria) this;
        }

        public Criteria andLowInterestGreaterThanOrEqualTo(Double value) {
            addCriterion("low_interest >=", value, "lowInterest");
            return (Criteria) this;
        }

        public Criteria andLowInterestLessThan(Double value) {
            addCriterion("low_interest <", value, "lowInterest");
            return (Criteria) this;
        }

        public Criteria andLowInterestLessThanOrEqualTo(Double value) {
            addCriterion("low_interest <=", value, "lowInterest");
            return (Criteria) this;
        }

        public Criteria andLowInterestIn(List<Double> values) {
            addCriterion("low_interest in", values, "lowInterest");
            return (Criteria) this;
        }

        public Criteria andLowInterestNotIn(List<Double> values) {
            addCriterion("low_interest not in", values, "lowInterest");
            return (Criteria) this;
        }

        public Criteria andLowInterestBetween(Double value1, Double value2) {
            addCriterion("low_interest between", value1, value2, "lowInterest");
            return (Criteria) this;
        }

        public Criteria andLowInterestNotBetween(Double value1, Double value2) {
            addCriterion("low_interest not between", value1, value2, "lowInterest");
            return (Criteria) this;
        }

        public Criteria andHighInterestIsNull() {
            addCriterion("high_interest is null");
            return (Criteria) this;
        }

        public Criteria andHighInterestIsNotNull() {
            addCriterion("high_interest is not null");
            return (Criteria) this;
        }

        public Criteria andHighInterestEqualTo(Double value) {
            addCriterion("high_interest =", value, "highInterest");
            return (Criteria) this;
        }

        public Criteria andHighInterestNotEqualTo(Double value) {
            addCriterion("high_interest <>", value, "highInterest");
            return (Criteria) this;
        }

        public Criteria andHighInterestGreaterThan(Double value) {
            addCriterion("high_interest >", value, "highInterest");
            return (Criteria) this;
        }

        public Criteria andHighInterestGreaterThanOrEqualTo(Double value) {
            addCriterion("high_interest >=", value, "highInterest");
            return (Criteria) this;
        }

        public Criteria andHighInterestLessThan(Double value) {
            addCriterion("high_interest <", value, "highInterest");
            return (Criteria) this;
        }

        public Criteria andHighInterestLessThanOrEqualTo(Double value) {
            addCriterion("high_interest <=", value, "highInterest");
            return (Criteria) this;
        }

        public Criteria andHighInterestIn(List<Double> values) {
            addCriterion("high_interest in", values, "highInterest");
            return (Criteria) this;
        }

        public Criteria andHighInterestNotIn(List<Double> values) {
            addCriterion("high_interest not in", values, "highInterest");
            return (Criteria) this;
        }

        public Criteria andHighInterestBetween(Double value1, Double value2) {
            addCriterion("high_interest between", value1, value2, "highInterest");
            return (Criteria) this;
        }

        public Criteria andHighInterestNotBetween(Double value1, Double value2) {
            addCriterion("high_interest not between", value1, value2, "highInterest");
            return (Criteria) this;
        }

        public Criteria andCreditAuthIsNull() {
            addCriterion("credit_auth is null");
            return (Criteria) this;
        }

        public Criteria andCreditAuthIsNotNull() {
            addCriterion("credit_auth is not null");
            return (Criteria) this;
        }

        public Criteria andCreditAuthEqualTo(String value) {
            addCriterion("credit_auth =", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthNotEqualTo(String value) {
            addCriterion("credit_auth <>", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthGreaterThan(String value) {
            addCriterion("credit_auth >", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthGreaterThanOrEqualTo(String value) {
            addCriterion("credit_auth >=", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthLessThan(String value) {
            addCriterion("credit_auth <", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthLessThanOrEqualTo(String value) {
            addCriterion("credit_auth <=", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthLike(String value) {
            addCriterion("credit_auth like", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthNotLike(String value) {
            addCriterion("credit_auth not like", value, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthIn(List<String> values) {
            addCriterion("credit_auth in", values, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthNotIn(List<String> values) {
            addCriterion("credit_auth not in", values, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthBetween(String value1, String value2) {
            addCriterion("credit_auth between", value1, value2, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andCreditAuthNotBetween(String value1, String value2) {
            addCriterion("credit_auth not between", value1, value2, "creditAuth");
            return (Criteria) this;
        }

        public Criteria andLenderNameIsNull() {
            addCriterion("lender_name is null");
            return (Criteria) this;
        }

        public Criteria andLenderNameIsNotNull() {
            addCriterion("lender_name is not null");
            return (Criteria) this;
        }

        public Criteria andLenderNameEqualTo(String value) {
            addCriterion("lender_name =", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameNotEqualTo(String value) {
            addCriterion("lender_name <>", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameGreaterThan(String value) {
            addCriterion("lender_name >", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameGreaterThanOrEqualTo(String value) {
            addCriterion("lender_name >=", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameLessThan(String value) {
            addCriterion("lender_name <", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameLessThanOrEqualTo(String value) {
            addCriterion("lender_name <=", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameLike(String value) {
            addCriterion("lender_name like", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameNotLike(String value) {
            addCriterion("lender_name not like", value, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameIn(List<String> values) {
            addCriterion("lender_name in", values, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameNotIn(List<String> values) {
            addCriterion("lender_name not in", values, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameBetween(String value1, String value2) {
            addCriterion("lender_name between", value1, value2, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderNameNotBetween(String value1, String value2) {
            addCriterion("lender_name not between", value1, value2, "lenderName");
            return (Criteria) this;
        }

        public Criteria andLenderDescIsNull() {
            addCriterion("lender_desc is null");
            return (Criteria) this;
        }

        public Criteria andLenderDescIsNotNull() {
            addCriterion("lender_desc is not null");
            return (Criteria) this;
        }

        public Criteria andLenderDescEqualTo(String value) {
            addCriterion("lender_desc =", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescNotEqualTo(String value) {
            addCriterion("lender_desc <>", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescGreaterThan(String value) {
            addCriterion("lender_desc >", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescGreaterThanOrEqualTo(String value) {
            addCriterion("lender_desc >=", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescLessThan(String value) {
            addCriterion("lender_desc <", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescLessThanOrEqualTo(String value) {
            addCriterion("lender_desc <=", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescLike(String value) {
            addCriterion("lender_desc like", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescNotLike(String value) {
            addCriterion("lender_desc not like", value, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescIn(List<String> values) {
            addCriterion("lender_desc in", values, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescNotIn(List<String> values) {
            addCriterion("lender_desc not in", values, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescBetween(String value1, String value2) {
            addCriterion("lender_desc between", value1, value2, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andLenderDescNotBetween(String value1, String value2) {
            addCriterion("lender_desc not between", value1, value2, "lenderDesc");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlIsNull() {
            addCriterion("active_captcha_url is null");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlIsNotNull() {
            addCriterion("active_captcha_url is not null");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlEqualTo(String value) {
            addCriterion("active_captcha_url =", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlNotEqualTo(String value) {
            addCriterion("active_captcha_url <>", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlGreaterThan(String value) {
            addCriterion("active_captcha_url >", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlGreaterThanOrEqualTo(String value) {
            addCriterion("active_captcha_url >=", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlLessThan(String value) {
            addCriterion("active_captcha_url <", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlLessThanOrEqualTo(String value) {
            addCriterion("active_captcha_url <=", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlLike(String value) {
            addCriterion("active_captcha_url like", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlNotLike(String value) {
            addCriterion("active_captcha_url not like", value, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlIn(List<String> values) {
            addCriterion("active_captcha_url in", values, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlNotIn(List<String> values) {
            addCriterion("active_captcha_url not in", values, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlBetween(String value1, String value2) {
            addCriterion("active_captcha_url between", value1, value2, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andActiveCaptchaUrlNotBetween(String value1, String value2) {
            addCriterion("active_captcha_url not between", value1, value2, "activeCaptchaUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlIsNull() {
            addCriterion("reg_interface_url is null");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlIsNotNull() {
            addCriterion("reg_interface_url is not null");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlEqualTo(String value) {
            addCriterion("reg_interface_url =", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlNotEqualTo(String value) {
            addCriterion("reg_interface_url <>", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlGreaterThan(String value) {
            addCriterion("reg_interface_url >", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlGreaterThanOrEqualTo(String value) {
            addCriterion("reg_interface_url >=", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlLessThan(String value) {
            addCriterion("reg_interface_url <", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlLessThanOrEqualTo(String value) {
            addCriterion("reg_interface_url <=", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlLike(String value) {
            addCriterion("reg_interface_url like", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlNotLike(String value) {
            addCriterion("reg_interface_url not like", value, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlIn(List<String> values) {
            addCriterion("reg_interface_url in", values, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlNotIn(List<String> values) {
            addCriterion("reg_interface_url not in", values, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlBetween(String value1, String value2) {
            addCriterion("reg_interface_url between", value1, value2, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andRegInterfaceUrlNotBetween(String value1, String value2) {
            addCriterion("reg_interface_url not between", value1, value2, "regInterfaceUrl");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNull() {
            addCriterion("publish_time is null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIsNotNull() {
            addCriterion("publish_time is not null");
            return (Criteria) this;
        }

        public Criteria andPublishTimeEqualTo(Date value) {
            addCriterion("publish_time =", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotEqualTo(Date value) {
            addCriterion("publish_time <>", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThan(Date value) {
            addCriterion("publish_time >", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("publish_time >=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThan(Date value) {
            addCriterion("publish_time <", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeLessThanOrEqualTo(Date value) {
            addCriterion("publish_time <=", value, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeIn(List<Date> values) {
            addCriterion("publish_time in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotIn(List<Date> values) {
            addCriterion("publish_time not in", values, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeBetween(Date value1, Date value2) {
            addCriterion("publish_time between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andPublishTimeNotBetween(Date value1, Date value2) {
            addCriterion("publish_time not between", value1, value2, "publishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeIsNull() {
            addCriterion("unpublish_time is null");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeIsNotNull() {
            addCriterion("unpublish_time is not null");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeEqualTo(Date value) {
            addCriterion("unpublish_time =", value, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeNotEqualTo(Date value) {
            addCriterion("unpublish_time <>", value, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeGreaterThan(Date value) {
            addCriterion("unpublish_time >", value, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("unpublish_time >=", value, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeLessThan(Date value) {
            addCriterion("unpublish_time <", value, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeLessThanOrEqualTo(Date value) {
            addCriterion("unpublish_time <=", value, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeIn(List<Date> values) {
            addCriterion("unpublish_time in", values, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeNotIn(List<Date> values) {
            addCriterion("unpublish_time not in", values, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeBetween(Date value1, Date value2) {
            addCriterion("unpublish_time between", value1, value2, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andUnpublishTimeNotBetween(Date value1, Date value2) {
            addCriterion("unpublish_time not between", value1, value2, "unpublishTime");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeIsNull() {
            addCriterion("display_type is null");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeIsNotNull() {
            addCriterion("display_type is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeEqualTo(Byte value) {
            addCriterion("display_type =", value, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeNotEqualTo(Byte value) {
            addCriterion("display_type <>", value, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeGreaterThan(Byte value) {
            addCriterion("display_type >", value, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("display_type >=", value, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeLessThan(Byte value) {
            addCriterion("display_type <", value, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeLessThanOrEqualTo(Byte value) {
            addCriterion("display_type <=", value, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeIn(List<Byte> values) {
            addCriterion("display_type in", values, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeNotIn(List<Byte> values) {
            addCriterion("display_type not in", values, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeBetween(Byte value1, Byte value2) {
            addCriterion("display_type between", value1, value2, "displayType");
            return (Criteria) this;
        }

        public Criteria andDisplayTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("display_type not between", value1, value2, "displayType");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdIsNull() {
            addCriterion("charge_mode_id is null");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdIsNotNull() {
            addCriterion("charge_mode_id is not null");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdEqualTo(Long value) {
            addCriterion("charge_mode_id =", value, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdNotEqualTo(Long value) {
            addCriterion("charge_mode_id <>", value, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdGreaterThan(Long value) {
            addCriterion("charge_mode_id >", value, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("charge_mode_id >=", value, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdLessThan(Long value) {
            addCriterion("charge_mode_id <", value, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdLessThanOrEqualTo(Long value) {
            addCriterion("charge_mode_id <=", value, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdIn(List<Long> values) {
            addCriterion("charge_mode_id in", values, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdNotIn(List<Long> values) {
            addCriterion("charge_mode_id not in", values, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdBetween(Long value1, Long value2) {
            addCriterion("charge_mode_id between", value1, value2, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andChargeModeIdNotBetween(Long value1, Long value2) {
            addCriterion("charge_mode_id not between", value1, value2, "chargeModeId");
            return (Criteria) this;
        }

        public Criteria andApplyTimesIsNull() {
            addCriterion("apply_times is null");
            return (Criteria) this;
        }

        public Criteria andApplyTimesIsNotNull() {
            addCriterion("apply_times is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTimesEqualTo(Integer value) {
            addCriterion("apply_times =", value, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesNotEqualTo(Integer value) {
            addCriterion("apply_times <>", value, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesGreaterThan(Integer value) {
            addCriterion("apply_times >", value, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("apply_times >=", value, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesLessThan(Integer value) {
            addCriterion("apply_times <", value, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesLessThanOrEqualTo(Integer value) {
            addCriterion("apply_times <=", value, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesIn(List<Integer> values) {
            addCriterion("apply_times in", values, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesNotIn(List<Integer> values) {
            addCriterion("apply_times not in", values, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesBetween(Integer value1, Integer value2) {
            addCriterion("apply_times between", value1, value2, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andApplyTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("apply_times not between", value1, value2, "applyTimes");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeIsNull() {
            addCriterion("loan_wait_time is null");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeIsNotNull() {
            addCriterion("loan_wait_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeEqualTo(Integer value) {
            addCriterion("loan_wait_time =", value, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeNotEqualTo(Integer value) {
            addCriterion("loan_wait_time <>", value, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeGreaterThan(Integer value) {
            addCriterion("loan_wait_time >", value, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("loan_wait_time >=", value, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeLessThan(Integer value) {
            addCriterion("loan_wait_time <", value, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeLessThanOrEqualTo(Integer value) {
            addCriterion("loan_wait_time <=", value, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeIn(List<Integer> values) {
            addCriterion("loan_wait_time in", values, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeNotIn(List<Integer> values) {
            addCriterion("loan_wait_time not in", values, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeBetween(Integer value1, Integer value2) {
            addCriterion("loan_wait_time between", value1, value2, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoanWaitTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("loan_wait_time not between", value1, value2, "loanWaitTime");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsIsNull() {
            addCriterion("app_client_ids is null");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsIsNotNull() {
            addCriterion("app_client_ids is not null");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsEqualTo(String value) {
            addCriterion("app_client_ids =", value, "appClientIds");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsNotEqualTo(String value) {
            addCriterion("app_client_ids <>", value, "appClientIds");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsGreaterThan(String value) {
            addCriterion("app_client_ids >", value, "appClientIds");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsGreaterThanOrEqualTo(String value) {
            addCriterion("app_client_ids >=", value, "appClientIds");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsLessThan(String value) {
            addCriterion("app_client_ids <", value, "appClientIds");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsLessThanOrEqualTo(String value) {
            addCriterion("app_client_ids <=", value, "appClientIds");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsLike(String value) {
            addCriterion("app_client_ids like", value, "appClientIds");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsNotLike(String value) {
            addCriterion("app_client_ids not like", value, "appClientIds");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsIn(List<String> values) {
            addCriterion("app_client_ids in", values, "appClientIds");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsNotIn(List<String> values) {
            addCriterion("app_client_ids not in", values, "appClientIds");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsBetween(String value1, String value2) {
            addCriterion("app_client_ids between", value1, value2, "appClientIds");
            return (Criteria) this;
        }

        public Criteria andAppClientIdsNotBetween(String value1, String value2) {
            addCriterion("app_client_ids not between", value1, value2, "appClientIds");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table product
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 08 11:34:49 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}