package com.pinganzhiyuan.model;

public class ProductKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
	 * @mbg.generated  Wed Jan 03 10:01:38 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.apply_times
	 * @mbg.generated  Wed Jan 03 10:01:38 CST 2018
	 */
	private Integer applyTimes;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.id
	 * @return  the value of product.id
	 * @mbg.generated  Wed Jan 03 10:01:38 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.id
	 * @param id  the value for product.id
	 * @mbg.generated  Wed Jan 03 10:01:38 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.apply_times
	 * @return  the value of product.apply_times
	 * @mbg.generated  Wed Jan 03 10:01:38 CST 2018
	 */
	public Integer getApplyTimes() {
		return applyTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.apply_times
	 * @param applyTimes  the value for product.apply_times
	 * @mbg.generated  Wed Jan 03 10:01:38 CST 2018
	 */
	public void setApplyTimes(Integer applyTimes) {
		this.applyTimes = applyTimes;
	}
}