package com.pinganzhiyuan.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class StandardStatementStatisticsExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    public StandardStatementStatisticsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStatisticDateIsNull() {
            addCriterion("statistic_date is null");
            return (Criteria) this;
        }

        public Criteria andStatisticDateIsNotNull() {
            addCriterion("statistic_date is not null");
            return (Criteria) this;
        }

        public Criteria andStatisticDateEqualTo(Date value) {
            addCriterionForJDBCDate("statistic_date =", value, "statisticDate");
            return (Criteria) this;
        }

        public Criteria andStatisticDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("statistic_date <>", value, "statisticDate");
            return (Criteria) this;
        }

        public Criteria andStatisticDateGreaterThan(Date value) {
            addCriterionForJDBCDate("statistic_date >", value, "statisticDate");
            return (Criteria) this;
        }

        public Criteria andStatisticDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("statistic_date >=", value, "statisticDate");
            return (Criteria) this;
        }

        public Criteria andStatisticDateLessThan(Date value) {
            addCriterionForJDBCDate("statistic_date <", value, "statisticDate");
            return (Criteria) this;
        }

        public Criteria andStatisticDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("statistic_date <=", value, "statisticDate");
            return (Criteria) this;
        }

        public Criteria andStatisticDateIn(List<Date> values) {
            addCriterionForJDBCDate("statistic_date in", values, "statisticDate");
            return (Criteria) this;
        }

        public Criteria andStatisticDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("statistic_date not in", values, "statisticDate");
            return (Criteria) this;
        }

        public Criteria andStatisticDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("statistic_date between", value1, value2, "statisticDate");
            return (Criteria) this;
        }

        public Criteria andStatisticDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("statistic_date not between", value1, value2, "statisticDate");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNull() {
            addCriterion("channel_name is null");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNotNull() {
            addCriterion("channel_name is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNameEqualTo(String value) {
            addCriterion("channel_name =", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotEqualTo(String value) {
            addCriterion("channel_name <>", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThan(String value) {
            addCriterion("channel_name >", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThanOrEqualTo(String value) {
            addCriterion("channel_name >=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThan(String value) {
            addCriterion("channel_name <", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThanOrEqualTo(String value) {
            addCriterion("channel_name <=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLike(String value) {
            addCriterion("channel_name like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotLike(String value) {
            addCriterion("channel_name not like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameIn(List<String> values) {
            addCriterion("channel_name in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotIn(List<String> values) {
            addCriterion("channel_name not in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameBetween(String value1, String value2) {
            addCriterion("channel_name between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotBetween(String value1, String value2) {
            addCriterion("channel_name not between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andAppProductNameIsNull() {
            addCriterion("app_product_name is null");
            return (Criteria) this;
        }

        public Criteria andAppProductNameIsNotNull() {
            addCriterion("app_product_name is not null");
            return (Criteria) this;
        }

        public Criteria andAppProductNameEqualTo(String value) {
            addCriterion("app_product_name =", value, "appProductName");
            return (Criteria) this;
        }

        public Criteria andAppProductNameNotEqualTo(String value) {
            addCriterion("app_product_name <>", value, "appProductName");
            return (Criteria) this;
        }

        public Criteria andAppProductNameGreaterThan(String value) {
            addCriterion("app_product_name >", value, "appProductName");
            return (Criteria) this;
        }

        public Criteria andAppProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("app_product_name >=", value, "appProductName");
            return (Criteria) this;
        }

        public Criteria andAppProductNameLessThan(String value) {
            addCriterion("app_product_name <", value, "appProductName");
            return (Criteria) this;
        }

        public Criteria andAppProductNameLessThanOrEqualTo(String value) {
            addCriterion("app_product_name <=", value, "appProductName");
            return (Criteria) this;
        }

        public Criteria andAppProductNameLike(String value) {
            addCriterion("app_product_name like", value, "appProductName");
            return (Criteria) this;
        }

        public Criteria andAppProductNameNotLike(String value) {
            addCriterion("app_product_name not like", value, "appProductName");
            return (Criteria) this;
        }

        public Criteria andAppProductNameIn(List<String> values) {
            addCriterion("app_product_name in", values, "appProductName");
            return (Criteria) this;
        }

        public Criteria andAppProductNameNotIn(List<String> values) {
            addCriterion("app_product_name not in", values, "appProductName");
            return (Criteria) this;
        }

        public Criteria andAppProductNameBetween(String value1, String value2) {
            addCriterion("app_product_name between", value1, value2, "appProductName");
            return (Criteria) this;
        }

        public Criteria andAppProductNameNotBetween(String value1, String value2) {
            addCriterion("app_product_name not between", value1, value2, "appProductName");
            return (Criteria) this;
        }

        public Criteria andNewDeviceCountIsNull() {
            addCriterion("new_device_count is null");
            return (Criteria) this;
        }

        public Criteria andNewDeviceCountIsNotNull() {
            addCriterion("new_device_count is not null");
            return (Criteria) this;
        }

        public Criteria andNewDeviceCountEqualTo(Integer value) {
            addCriterion("new_device_count =", value, "newDeviceCount");
            return (Criteria) this;
        }

        public Criteria andNewDeviceCountNotEqualTo(Integer value) {
            addCriterion("new_device_count <>", value, "newDeviceCount");
            return (Criteria) this;
        }

        public Criteria andNewDeviceCountGreaterThan(Integer value) {
            addCriterion("new_device_count >", value, "newDeviceCount");
            return (Criteria) this;
        }

        public Criteria andNewDeviceCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("new_device_count >=", value, "newDeviceCount");
            return (Criteria) this;
        }

        public Criteria andNewDeviceCountLessThan(Integer value) {
            addCriterion("new_device_count <", value, "newDeviceCount");
            return (Criteria) this;
        }

        public Criteria andNewDeviceCountLessThanOrEqualTo(Integer value) {
            addCriterion("new_device_count <=", value, "newDeviceCount");
            return (Criteria) this;
        }

        public Criteria andNewDeviceCountIn(List<Integer> values) {
            addCriterion("new_device_count in", values, "newDeviceCount");
            return (Criteria) this;
        }

        public Criteria andNewDeviceCountNotIn(List<Integer> values) {
            addCriterion("new_device_count not in", values, "newDeviceCount");
            return (Criteria) this;
        }

        public Criteria andNewDeviceCountBetween(Integer value1, Integer value2) {
            addCriterion("new_device_count between", value1, value2, "newDeviceCount");
            return (Criteria) this;
        }

        public Criteria andNewDeviceCountNotBetween(Integer value1, Integer value2) {
            addCriterion("new_device_count not between", value1, value2, "newDeviceCount");
            return (Criteria) this;
        }

        public Criteria andNewUserCountIsNull() {
            addCriterion("new_user_count is null");
            return (Criteria) this;
        }

        public Criteria andNewUserCountIsNotNull() {
            addCriterion("new_user_count is not null");
            return (Criteria) this;
        }

        public Criteria andNewUserCountEqualTo(Integer value) {
            addCriterion("new_user_count =", value, "newUserCount");
            return (Criteria) this;
        }

        public Criteria andNewUserCountNotEqualTo(Integer value) {
            addCriterion("new_user_count <>", value, "newUserCount");
            return (Criteria) this;
        }

        public Criteria andNewUserCountGreaterThan(Integer value) {
            addCriterion("new_user_count >", value, "newUserCount");
            return (Criteria) this;
        }

        public Criteria andNewUserCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("new_user_count >=", value, "newUserCount");
            return (Criteria) this;
        }

        public Criteria andNewUserCountLessThan(Integer value) {
            addCriterion("new_user_count <", value, "newUserCount");
            return (Criteria) this;
        }

        public Criteria andNewUserCountLessThanOrEqualTo(Integer value) {
            addCriterion("new_user_count <=", value, "newUserCount");
            return (Criteria) this;
        }

        public Criteria andNewUserCountIn(List<Integer> values) {
            addCriterion("new_user_count in", values, "newUserCount");
            return (Criteria) this;
        }

        public Criteria andNewUserCountNotIn(List<Integer> values) {
            addCriterion("new_user_count not in", values, "newUserCount");
            return (Criteria) this;
        }

        public Criteria andNewUserCountBetween(Integer value1, Integer value2) {
            addCriterion("new_user_count between", value1, value2, "newUserCount");
            return (Criteria) this;
        }

        public Criteria andNewUserCountNotBetween(Integer value1, Integer value2) {
            addCriterion("new_user_count not between", value1, value2, "newUserCount");
            return (Criteria) this;
        }

        public Criteria andNewUserProductUvCountIsNull() {
            addCriterion("new_user_product_uv_count is null");
            return (Criteria) this;
        }

        public Criteria andNewUserProductUvCountIsNotNull() {
            addCriterion("new_user_product_uv_count is not null");
            return (Criteria) this;
        }

        public Criteria andNewUserProductUvCountEqualTo(Integer value) {
            addCriterion("new_user_product_uv_count =", value, "newUserProductUvCount");
            return (Criteria) this;
        }

        public Criteria andNewUserProductUvCountNotEqualTo(Integer value) {
            addCriterion("new_user_product_uv_count <>", value, "newUserProductUvCount");
            return (Criteria) this;
        }

        public Criteria andNewUserProductUvCountGreaterThan(Integer value) {
            addCriterion("new_user_product_uv_count >", value, "newUserProductUvCount");
            return (Criteria) this;
        }

        public Criteria andNewUserProductUvCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("new_user_product_uv_count >=", value, "newUserProductUvCount");
            return (Criteria) this;
        }

        public Criteria andNewUserProductUvCountLessThan(Integer value) {
            addCriterion("new_user_product_uv_count <", value, "newUserProductUvCount");
            return (Criteria) this;
        }

        public Criteria andNewUserProductUvCountLessThanOrEqualTo(Integer value) {
            addCriterion("new_user_product_uv_count <=", value, "newUserProductUvCount");
            return (Criteria) this;
        }

        public Criteria andNewUserProductUvCountIn(List<Integer> values) {
            addCriterion("new_user_product_uv_count in", values, "newUserProductUvCount");
            return (Criteria) this;
        }

        public Criteria andNewUserProductUvCountNotIn(List<Integer> values) {
            addCriterion("new_user_product_uv_count not in", values, "newUserProductUvCount");
            return (Criteria) this;
        }

        public Criteria andNewUserProductUvCountBetween(Integer value1, Integer value2) {
            addCriterion("new_user_product_uv_count between", value1, value2, "newUserProductUvCount");
            return (Criteria) this;
        }

        public Criteria andNewUserProductUvCountNotBetween(Integer value1, Integer value2) {
            addCriterion("new_user_product_uv_count not between", value1, value2, "newUserProductUvCount");
            return (Criteria) this;
        }

        public Criteria andActiveDeviceCountIsNull() {
            addCriterion("active_device_count is null");
            return (Criteria) this;
        }

        public Criteria andActiveDeviceCountIsNotNull() {
            addCriterion("active_device_count is not null");
            return (Criteria) this;
        }

        public Criteria andActiveDeviceCountEqualTo(Integer value) {
            addCriterion("active_device_count =", value, "activeDeviceCount");
            return (Criteria) this;
        }

        public Criteria andActiveDeviceCountNotEqualTo(Integer value) {
            addCriterion("active_device_count <>", value, "activeDeviceCount");
            return (Criteria) this;
        }

        public Criteria andActiveDeviceCountGreaterThan(Integer value) {
            addCriterion("active_device_count >", value, "activeDeviceCount");
            return (Criteria) this;
        }

        public Criteria andActiveDeviceCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("active_device_count >=", value, "activeDeviceCount");
            return (Criteria) this;
        }

        public Criteria andActiveDeviceCountLessThan(Integer value) {
            addCriterion("active_device_count <", value, "activeDeviceCount");
            return (Criteria) this;
        }

        public Criteria andActiveDeviceCountLessThanOrEqualTo(Integer value) {
            addCriterion("active_device_count <=", value, "activeDeviceCount");
            return (Criteria) this;
        }

        public Criteria andActiveDeviceCountIn(List<Integer> values) {
            addCriterion("active_device_count in", values, "activeDeviceCount");
            return (Criteria) this;
        }

        public Criteria andActiveDeviceCountNotIn(List<Integer> values) {
            addCriterion("active_device_count not in", values, "activeDeviceCount");
            return (Criteria) this;
        }

        public Criteria andActiveDeviceCountBetween(Integer value1, Integer value2) {
            addCriterion("active_device_count between", value1, value2, "activeDeviceCount");
            return (Criteria) this;
        }

        public Criteria andActiveDeviceCountNotBetween(Integer value1, Integer value2) {
            addCriterion("active_device_count not between", value1, value2, "activeDeviceCount");
            return (Criteria) this;
        }

        public Criteria andActiveUserCountIsNull() {
            addCriterion("active_user_count is null");
            return (Criteria) this;
        }

        public Criteria andActiveUserCountIsNotNull() {
            addCriterion("active_user_count is not null");
            return (Criteria) this;
        }

        public Criteria andActiveUserCountEqualTo(Integer value) {
            addCriterion("active_user_count =", value, "activeUserCount");
            return (Criteria) this;
        }

        public Criteria andActiveUserCountNotEqualTo(Integer value) {
            addCriterion("active_user_count <>", value, "activeUserCount");
            return (Criteria) this;
        }

        public Criteria andActiveUserCountGreaterThan(Integer value) {
            addCriterion("active_user_count >", value, "activeUserCount");
            return (Criteria) this;
        }

        public Criteria andActiveUserCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("active_user_count >=", value, "activeUserCount");
            return (Criteria) this;
        }

        public Criteria andActiveUserCountLessThan(Integer value) {
            addCriterion("active_user_count <", value, "activeUserCount");
            return (Criteria) this;
        }

        public Criteria andActiveUserCountLessThanOrEqualTo(Integer value) {
            addCriterion("active_user_count <=", value, "activeUserCount");
            return (Criteria) this;
        }

        public Criteria andActiveUserCountIn(List<Integer> values) {
            addCriterion("active_user_count in", values, "activeUserCount");
            return (Criteria) this;
        }

        public Criteria andActiveUserCountNotIn(List<Integer> values) {
            addCriterion("active_user_count not in", values, "activeUserCount");
            return (Criteria) this;
        }

        public Criteria andActiveUserCountBetween(Integer value1, Integer value2) {
            addCriterion("active_user_count between", value1, value2, "activeUserCount");
            return (Criteria) this;
        }

        public Criteria andActiveUserCountNotBetween(Integer value1, Integer value2) {
            addCriterion("active_user_count not between", value1, value2, "activeUserCount");
            return (Criteria) this;
        }

        public Criteria andAllProductUvCountIsNull() {
            addCriterion("all_product_uv_count is null");
            return (Criteria) this;
        }

        public Criteria andAllProductUvCountIsNotNull() {
            addCriterion("all_product_uv_count is not null");
            return (Criteria) this;
        }

        public Criteria andAllProductUvCountEqualTo(Integer value) {
            addCriterion("all_product_uv_count =", value, "allProductUvCount");
            return (Criteria) this;
        }

        public Criteria andAllProductUvCountNotEqualTo(Integer value) {
            addCriterion("all_product_uv_count <>", value, "allProductUvCount");
            return (Criteria) this;
        }

        public Criteria andAllProductUvCountGreaterThan(Integer value) {
            addCriterion("all_product_uv_count >", value, "allProductUvCount");
            return (Criteria) this;
        }

        public Criteria andAllProductUvCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("all_product_uv_count >=", value, "allProductUvCount");
            return (Criteria) this;
        }

        public Criteria andAllProductUvCountLessThan(Integer value) {
            addCriterion("all_product_uv_count <", value, "allProductUvCount");
            return (Criteria) this;
        }

        public Criteria andAllProductUvCountLessThanOrEqualTo(Integer value) {
            addCriterion("all_product_uv_count <=", value, "allProductUvCount");
            return (Criteria) this;
        }

        public Criteria andAllProductUvCountIn(List<Integer> values) {
            addCriterion("all_product_uv_count in", values, "allProductUvCount");
            return (Criteria) this;
        }

        public Criteria andAllProductUvCountNotIn(List<Integer> values) {
            addCriterion("all_product_uv_count not in", values, "allProductUvCount");
            return (Criteria) this;
        }

        public Criteria andAllProductUvCountBetween(Integer value1, Integer value2) {
            addCriterion("all_product_uv_count between", value1, value2, "allProductUvCount");
            return (Criteria) this;
        }

        public Criteria andAllProductUvCountNotBetween(Integer value1, Integer value2) {
            addCriterion("all_product_uv_count not between", value1, value2, "allProductUvCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table standard_statement_statistics
     * @mbg.generated  Mon Jan 22 22:10:09 CST 2018
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table standard_statement_statistics
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 09 10:58:40 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}