package com.pinganzhiyuan.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StatisticDateTransformExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    public StatisticDateTransformExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("device_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(Long value) {
            addCriterion("device_id =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(Long value) {
            addCriterion("device_id <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(Long value) {
            addCriterion("device_id >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("device_id >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(Long value) {
            addCriterion("device_id <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(Long value) {
            addCriterion("device_id <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<Long> values) {
            addCriterion("device_id in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<Long> values) {
            addCriterion("device_id not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(Long value1, Long value2) {
            addCriterion("device_id between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(Long value1, Long value2) {
            addCriterion("device_id not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andSidIsNull() {
            addCriterion("sid is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("sid is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(String value) {
            addCriterion("sid =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(String value) {
            addCriterion("sid <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(String value) {
            addCriterion("sid >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(String value) {
            addCriterion("sid >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(String value) {
            addCriterion("sid <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(String value) {
            addCriterion("sid <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLike(String value) {
            addCriterion("sid like", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotLike(String value) {
            addCriterion("sid not like", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<String> values) {
            addCriterion("sid in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<String> values) {
            addCriterion("sid not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(String value1, String value2) {
            addCriterion("sid between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(String value1, String value2) {
            addCriterion("sid not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Long value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Long value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Long value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Long value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Long value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Long> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Long> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Long value1, Long value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Long value1, Long value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductUrlIsNull() {
            addCriterion("product_url is null");
            return (Criteria) this;
        }

        public Criteria andProductUrlIsNotNull() {
            addCriterion("product_url is not null");
            return (Criteria) this;
        }

        public Criteria andProductUrlEqualTo(String value) {
            addCriterion("product_url =", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlNotEqualTo(String value) {
            addCriterion("product_url <>", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlGreaterThan(String value) {
            addCriterion("product_url >", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlGreaterThanOrEqualTo(String value) {
            addCriterion("product_url >=", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlLessThan(String value) {
            addCriterion("product_url <", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlLessThanOrEqualTo(String value) {
            addCriterion("product_url <=", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlLike(String value) {
            addCriterion("product_url like", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlNotLike(String value) {
            addCriterion("product_url not like", value, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlIn(List<String> values) {
            addCriterion("product_url in", values, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlNotIn(List<String> values) {
            addCriterion("product_url not in", values, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlBetween(String value1, String value2) {
            addCriterion("product_url between", value1, value2, "productUrl");
            return (Criteria) this;
        }

        public Criteria andProductUrlNotBetween(String value1, String value2) {
            addCriterion("product_url not between", value1, value2, "productUrl");
            return (Criteria) this;
        }

        public Criteria andStartVisitTimeIsNull() {
            addCriterion("start_visit_time is null");
            return (Criteria) this;
        }

        public Criteria andStartVisitTimeIsNotNull() {
            addCriterion("start_visit_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartVisitTimeEqualTo(Date value) {
            addCriterion("start_visit_time =", value, "startVisitTime");
            return (Criteria) this;
        }

        public Criteria andStartVisitTimeNotEqualTo(Date value) {
            addCriterion("start_visit_time <>", value, "startVisitTime");
            return (Criteria) this;
        }

        public Criteria andStartVisitTimeGreaterThan(Date value) {
            addCriterion("start_visit_time >", value, "startVisitTime");
            return (Criteria) this;
        }

        public Criteria andStartVisitTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_visit_time >=", value, "startVisitTime");
            return (Criteria) this;
        }

        public Criteria andStartVisitTimeLessThan(Date value) {
            addCriterion("start_visit_time <", value, "startVisitTime");
            return (Criteria) this;
        }

        public Criteria andStartVisitTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_visit_time <=", value, "startVisitTime");
            return (Criteria) this;
        }

        public Criteria andStartVisitTimeIn(List<Date> values) {
            addCriterion("start_visit_time in", values, "startVisitTime");
            return (Criteria) this;
        }

        public Criteria andStartVisitTimeNotIn(List<Date> values) {
            addCriterion("start_visit_time not in", values, "startVisitTime");
            return (Criteria) this;
        }

        public Criteria andStartVisitTimeBetween(Date value1, Date value2) {
            addCriterion("start_visit_time between", value1, value2, "startVisitTime");
            return (Criteria) this;
        }

        public Criteria andStartVisitTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_visit_time not between", value1, value2, "startVisitTime");
            return (Criteria) this;
        }

        public Criteria andEndVisitTimeIsNull() {
            addCriterion("end_visit_time is null");
            return (Criteria) this;
        }

        public Criteria andEndVisitTimeIsNotNull() {
            addCriterion("end_visit_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndVisitTimeEqualTo(Date value) {
            addCriterion("end_visit_time =", value, "endVisitTime");
            return (Criteria) this;
        }

        public Criteria andEndVisitTimeNotEqualTo(Date value) {
            addCriterion("end_visit_time <>", value, "endVisitTime");
            return (Criteria) this;
        }

        public Criteria andEndVisitTimeGreaterThan(Date value) {
            addCriterion("end_visit_time >", value, "endVisitTime");
            return (Criteria) this;
        }

        public Criteria andEndVisitTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_visit_time >=", value, "endVisitTime");
            return (Criteria) this;
        }

        public Criteria andEndVisitTimeLessThan(Date value) {
            addCriterion("end_visit_time <", value, "endVisitTime");
            return (Criteria) this;
        }

        public Criteria andEndVisitTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_visit_time <=", value, "endVisitTime");
            return (Criteria) this;
        }

        public Criteria andEndVisitTimeIn(List<Date> values) {
            addCriterion("end_visit_time in", values, "endVisitTime");
            return (Criteria) this;
        }

        public Criteria andEndVisitTimeNotIn(List<Date> values) {
            addCriterion("end_visit_time not in", values, "endVisitTime");
            return (Criteria) this;
        }

        public Criteria andEndVisitTimeBetween(Date value1, Date value2) {
            addCriterion("end_visit_time between", value1, value2, "endVisitTime");
            return (Criteria) this;
        }

        public Criteria andEndVisitTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_visit_time not between", value1, value2, "endVisitTime");
            return (Criteria) this;
        }

        public Criteria andStayTimeIsNull() {
            addCriterion("stay_time is null");
            return (Criteria) this;
        }

        public Criteria andStayTimeIsNotNull() {
            addCriterion("stay_time is not null");
            return (Criteria) this;
        }

        public Criteria andStayTimeEqualTo(Integer value) {
            addCriterion("stay_time =", value, "stayTime");
            return (Criteria) this;
        }

        public Criteria andStayTimeNotEqualTo(Integer value) {
            addCriterion("stay_time <>", value, "stayTime");
            return (Criteria) this;
        }

        public Criteria andStayTimeGreaterThan(Integer value) {
            addCriterion("stay_time >", value, "stayTime");
            return (Criteria) this;
        }

        public Criteria andStayTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("stay_time >=", value, "stayTime");
            return (Criteria) this;
        }

        public Criteria andStayTimeLessThan(Integer value) {
            addCriterion("stay_time <", value, "stayTime");
            return (Criteria) this;
        }

        public Criteria andStayTimeLessThanOrEqualTo(Integer value) {
            addCriterion("stay_time <=", value, "stayTime");
            return (Criteria) this;
        }

        public Criteria andStayTimeIn(List<Integer> values) {
            addCriterion("stay_time in", values, "stayTime");
            return (Criteria) this;
        }

        public Criteria andStayTimeNotIn(List<Integer> values) {
            addCriterion("stay_time not in", values, "stayTime");
            return (Criteria) this;
        }

        public Criteria andStayTimeBetween(Integer value1, Integer value2) {
            addCriterion("stay_time between", value1, value2, "stayTime");
            return (Criteria) this;
        }

        public Criteria andStayTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("stay_time not between", value1, value2, "stayTime");
            return (Criteria) this;
        }

        public Criteria andIsRequestCodeIsNull() {
            addCriterion("is_request_code is null");
            return (Criteria) this;
        }

        public Criteria andIsRequestCodeIsNotNull() {
            addCriterion("is_request_code is not null");
            return (Criteria) this;
        }

        public Criteria andIsRequestCodeEqualTo(Boolean value) {
            addCriterion("is_request_code =", value, "isRequestCode");
            return (Criteria) this;
        }

        public Criteria andIsRequestCodeNotEqualTo(Boolean value) {
            addCriterion("is_request_code <>", value, "isRequestCode");
            return (Criteria) this;
        }

        public Criteria andIsRequestCodeGreaterThan(Boolean value) {
            addCriterion("is_request_code >", value, "isRequestCode");
            return (Criteria) this;
        }

        public Criteria andIsRequestCodeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_request_code >=", value, "isRequestCode");
            return (Criteria) this;
        }

        public Criteria andIsRequestCodeLessThan(Boolean value) {
            addCriterion("is_request_code <", value, "isRequestCode");
            return (Criteria) this;
        }

        public Criteria andIsRequestCodeLessThanOrEqualTo(Boolean value) {
            addCriterion("is_request_code <=", value, "isRequestCode");
            return (Criteria) this;
        }

        public Criteria andIsRequestCodeIn(List<Boolean> values) {
            addCriterion("is_request_code in", values, "isRequestCode");
            return (Criteria) this;
        }

        public Criteria andIsRequestCodeNotIn(List<Boolean> values) {
            addCriterion("is_request_code not in", values, "isRequestCode");
            return (Criteria) this;
        }

        public Criteria andIsRequestCodeBetween(Boolean value1, Boolean value2) {
            addCriterion("is_request_code between", value1, value2, "isRequestCode");
            return (Criteria) this;
        }

        public Criteria andIsRequestCodeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_request_code not between", value1, value2, "isRequestCode");
            return (Criteria) this;
        }

        public Criteria andAcquireCodeTimeIsNull() {
            addCriterion("acquire_code_time is null");
            return (Criteria) this;
        }

        public Criteria andAcquireCodeTimeIsNotNull() {
            addCriterion("acquire_code_time is not null");
            return (Criteria) this;
        }

        public Criteria andAcquireCodeTimeEqualTo(Date value) {
            addCriterion("acquire_code_time =", value, "acquireCodeTime");
            return (Criteria) this;
        }

        public Criteria andAcquireCodeTimeNotEqualTo(Date value) {
            addCriterion("acquire_code_time <>", value, "acquireCodeTime");
            return (Criteria) this;
        }

        public Criteria andAcquireCodeTimeGreaterThan(Date value) {
            addCriterion("acquire_code_time >", value, "acquireCodeTime");
            return (Criteria) this;
        }

        public Criteria andAcquireCodeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("acquire_code_time >=", value, "acquireCodeTime");
            return (Criteria) this;
        }

        public Criteria andAcquireCodeTimeLessThan(Date value) {
            addCriterion("acquire_code_time <", value, "acquireCodeTime");
            return (Criteria) this;
        }

        public Criteria andAcquireCodeTimeLessThanOrEqualTo(Date value) {
            addCriterion("acquire_code_time <=", value, "acquireCodeTime");
            return (Criteria) this;
        }

        public Criteria andAcquireCodeTimeIn(List<Date> values) {
            addCriterion("acquire_code_time in", values, "acquireCodeTime");
            return (Criteria) this;
        }

        public Criteria andAcquireCodeTimeNotIn(List<Date> values) {
            addCriterion("acquire_code_time not in", values, "acquireCodeTime");
            return (Criteria) this;
        }

        public Criteria andAcquireCodeTimeBetween(Date value1, Date value2) {
            addCriterion("acquire_code_time between", value1, value2, "acquireCodeTime");
            return (Criteria) this;
        }

        public Criteria andAcquireCodeTimeNotBetween(Date value1, Date value2) {
            addCriterion("acquire_code_time not between", value1, value2, "acquireCodeTime");
            return (Criteria) this;
        }

        public Criteria andIsRequestRegisterIsNull() {
            addCriterion("is_request_register is null");
            return (Criteria) this;
        }

        public Criteria andIsRequestRegisterIsNotNull() {
            addCriterion("is_request_register is not null");
            return (Criteria) this;
        }

        public Criteria andIsRequestRegisterEqualTo(Boolean value) {
            addCriterion("is_request_register =", value, "isRequestRegister");
            return (Criteria) this;
        }

        public Criteria andIsRequestRegisterNotEqualTo(Boolean value) {
            addCriterion("is_request_register <>", value, "isRequestRegister");
            return (Criteria) this;
        }

        public Criteria andIsRequestRegisterGreaterThan(Boolean value) {
            addCriterion("is_request_register >", value, "isRequestRegister");
            return (Criteria) this;
        }

        public Criteria andIsRequestRegisterGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_request_register >=", value, "isRequestRegister");
            return (Criteria) this;
        }

        public Criteria andIsRequestRegisterLessThan(Boolean value) {
            addCriterion("is_request_register <", value, "isRequestRegister");
            return (Criteria) this;
        }

        public Criteria andIsRequestRegisterLessThanOrEqualTo(Boolean value) {
            addCriterion("is_request_register <=", value, "isRequestRegister");
            return (Criteria) this;
        }

        public Criteria andIsRequestRegisterIn(List<Boolean> values) {
            addCriterion("is_request_register in", values, "isRequestRegister");
            return (Criteria) this;
        }

        public Criteria andIsRequestRegisterNotIn(List<Boolean> values) {
            addCriterion("is_request_register not in", values, "isRequestRegister");
            return (Criteria) this;
        }

        public Criteria andIsRequestRegisterBetween(Boolean value1, Boolean value2) {
            addCriterion("is_request_register between", value1, value2, "isRequestRegister");
            return (Criteria) this;
        }

        public Criteria andIsRequestRegisterNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_request_register not between", value1, value2, "isRequestRegister");
            return (Criteria) this;
        }

        public Criteria andSubmitRegisterTimeIsNull() {
            addCriterion("submit_register_time is null");
            return (Criteria) this;
        }

        public Criteria andSubmitRegisterTimeIsNotNull() {
            addCriterion("submit_register_time is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitRegisterTimeEqualTo(Date value) {
            addCriterion("submit_register_time =", value, "submitRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSubmitRegisterTimeNotEqualTo(Date value) {
            addCriterion("submit_register_time <>", value, "submitRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSubmitRegisterTimeGreaterThan(Date value) {
            addCriterion("submit_register_time >", value, "submitRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSubmitRegisterTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("submit_register_time >=", value, "submitRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSubmitRegisterTimeLessThan(Date value) {
            addCriterion("submit_register_time <", value, "submitRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSubmitRegisterTimeLessThanOrEqualTo(Date value) {
            addCriterion("submit_register_time <=", value, "submitRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSubmitRegisterTimeIn(List<Date> values) {
            addCriterion("submit_register_time in", values, "submitRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSubmitRegisterTimeNotIn(List<Date> values) {
            addCriterion("submit_register_time not in", values, "submitRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSubmitRegisterTimeBetween(Date value1, Date value2) {
            addCriterion("submit_register_time between", value1, value2, "submitRegisterTime");
            return (Criteria) this;
        }

        public Criteria andSubmitRegisterTimeNotBetween(Date value1, Date value2) {
            addCriterion("submit_register_time not between", value1, value2, "submitRegisterTime");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table statistic_date_transform
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table statistic_date_transform
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 03 10:01:38 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}