package com.pinganzhiyuan.model;

public class TopRightEntry {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column top_right_entry.id
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column top_right_entry.title
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column top_right_entry.subtitle
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    private String subtitle;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column top_right_entry.icon_url
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    private String iconUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column top_right_entry.url
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column top_right_entry.id
     * @return  the value of top_right_entry.id
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column top_right_entry.id
     * @param id  the value for top_right_entry.id
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column top_right_entry.title
     * @return  the value of top_right_entry.title
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column top_right_entry.title
     * @param title  the value for top_right_entry.title
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column top_right_entry.subtitle
     * @return  the value of top_right_entry.subtitle
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column top_right_entry.subtitle
     * @param subtitle  the value for top_right_entry.subtitle
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column top_right_entry.icon_url
     * @return  the value of top_right_entry.icon_url
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column top_right_entry.icon_url
     * @param iconUrl  the value for top_right_entry.icon_url
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column top_right_entry.url
     * @return  the value of top_right_entry.url
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column top_right_entry.url
     * @param url  the value for top_right_entry.url
     * @mbg.generated  Mon Feb 05 09:45:08 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }
}