package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.AppClient;
import com.pinganzhiyuan.model.AppClientExample;
import com.pinganzhiyuan.model.Channel;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface AppClientMapper {
    
    
//    /**
//     * 查询所有app+渠道的记录
//     * @return
//     */
//    @Select({
//        "select a.id as id, a.name, \n" + 
//        "a.package_name, a.channel_id, b.`name` as channel_name \n" + 
//        "from app_client a join channel b on a.channel_id = b.id"
//    })
//    @ResultMap("com.pinganzhiyuan.mapper.AppClientMapper.BaseResultMap")
//    List<AppClient> selectAllWithChannel();
    
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_client
	 * @mbg.generated  Wed Mar 07 15:51:36 CST 2018
	 */
	long countByExample(AppClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_client
	 * @mbg.generated  Wed Mar 07 15:51:36 CST 2018
	 */
	int deleteByExample(AppClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_client
	 * @mbg.generated  Wed Mar 07 15:51:36 CST 2018
	 */
	@Delete({ "delete from app_client", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_client
	 * @mbg.generated  Wed Mar 07 15:51:36 CST 2018
	 */
	@Insert({ "insert into app_client (name, package_name, ", "channel_id)",
			"values (#{name,jdbcType=VARCHAR}, #{packageName,jdbcType=VARCHAR}, ", "#{channelId,jdbcType=BIGINT})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(AppClient record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_client
	 * @mbg.generated  Wed Mar 07 15:51:36 CST 2018
	 */
	int insertSelective(AppClient record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_client
	 * @mbg.generated  Wed Mar 07 15:51:36 CST 2018
	 */
	List<AppClient> selectByExample(AppClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_client
	 * @mbg.generated  Wed Mar 07 15:51:36 CST 2018
	 */
	@Select({ "select", "id, name, package_name, channel_id", "from app_client", "where id = #{id,jdbcType=BIGINT}" })
	@ResultMap("com.pinganzhiyuan.mapper.AppClientMapper.BaseResultMap")
	AppClient selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_client
	 * @mbg.generated  Wed Mar 07 15:51:36 CST 2018
	 */
	int updateByExampleSelective(@Param("record") AppClient record, @Param("example") AppClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_client
	 * @mbg.generated  Wed Mar 07 15:51:36 CST 2018
	 */
	int updateByExample(@Param("record") AppClient record, @Param("example") AppClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_client
	 * @mbg.generated  Wed Mar 07 15:51:36 CST 2018
	 */
	int updateByPrimaryKeySelective(AppClient record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_client
	 * @mbg.generated  Wed Mar 07 15:51:36 CST 2018
	 */
	@Update({ "update app_client", "set name = #{name,jdbcType=VARCHAR},",
			"package_name = #{packageName,jdbcType=VARCHAR},", "channel_id = #{channelId,jdbcType=BIGINT}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(AppClient record);

	/**
     * 查询所有app+渠道的记录
     * @return
     */
    @Select({
    			"select a.id as id, a.name, \n" + 
    	        "a.package_name, a.channel_id, b.`name` as channel_name \n" + 
    	        "from app_client a join channel b on a.channel_id = b.id"
    })
    @ResultMap("com.pinganzhiyuan.mapper.AppClientMapper.BaseResultMap")
    List<AppClient> selectAllGroupByNameAndPackageName();
    
    /**
     * 查询当个产品的发布到的app+渠道的记录
     * @return
     */
    @Select({
        "select a.id as id, a.name, \n" + 
        "a.package_name, a.channel_id, b.`name` as channel_name \n" + 
        "from app_client a join channel b on a.channel_id = b.id\n" + 
        "where a.id in (${appIds});"
    })
    @ResultMap("com.pinganzhiyuan.mapper.AppClientMapper.BaseResultMap")
    List<AppClient> selectSingleProductWithChannel(@Param("appIds") String appIds);
    
    @Select({ "${queryString}" })
    @ResultMap("com.pinganzhiyuan.mapper.AppClientMapper.BaseResultMap")
    List<AppClient> selectByAppNamesAndChannelNames(@Param("queryString") String queryString);

    /**
     * 根据渠道获取到 appClient 集合
     * @param channelId
     * @return
     */
    @Select({ "select b.* " + 
    		"from client_version a join app_client b on b.name = a.name and b.package_name = a.package_name \n" + 
    		"where a.channel_id = #{channelId} group by  a.name, a.package_name" })
    @ResultMap("com.pinganzhiyuan.mapper.AppClientMapper.BaseResultMap")
	List<AppClient> selectByChannelId(@Param("channelId") String channelId);
}