package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.DeviceStatisticDaily;
import com.pinganzhiyuan.model.DeviceStatisticDailyExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface DeviceStatisticDailyMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_device_daily
     * @mbg.generated  Wed Jan 24 18:30:45 CST 2018
     */
    long countByExample(DeviceStatisticDailyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_device_daily
     * @mbg.generated  Wed Jan 24 18:30:45 CST 2018
     */
    int deleteByExample(DeviceStatisticDailyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_device_daily
     * @mbg.generated  Wed Jan 24 18:30:45 CST 2018
     */
    @Delete({ "delete from statistic_device_daily", "where id = #{id,jdbcType=BIGINT}" })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_device_daily
     * @mbg.generated  Wed Jan 24 18:30:45 CST 2018
     */
    @Insert({ "insert into statistic_device_daily (statistic_date, channel_id, ", "channel_name, app_product_id, ",
            "app_product_name, activate_device_count, ", "created_at)",
            "values (#{statisticDate,jdbcType=DATE}, #{channelId,jdbcType=BIGINT}, ",
            "#{channelName,jdbcType=VARCHAR}, #{appProductId,jdbcType=BIGINT}, ",
            "#{appProductName,jdbcType=VARCHAR}, #{activateDeviceCount,jdbcType=INTEGER}, ",
            "#{createdAt,jdbcType=TIMESTAMP})" })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(DeviceStatisticDaily record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_device_daily
     * @mbg.generated  Wed Jan 24 18:30:45 CST 2018
     */
    int insertSelective(DeviceStatisticDaily record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_device_daily
     * @mbg.generated  Wed Jan 24 18:30:45 CST 2018
     */
    List<DeviceStatisticDaily> selectByExample(DeviceStatisticDailyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_device_daily
     * @mbg.generated  Wed Jan 24 18:30:45 CST 2018
     */
    @Select({ "select", "id, statistic_date, channel_id, channel_name, app_product_id, app_product_name, ",
            "activate_device_count, created_at", "from statistic_device_daily", "where id = #{id,jdbcType=BIGINT}" })
    @ResultMap("com.pinganzhiyuan.mapper.DeviceStatisticDailyMapper.BaseResultMap")
    DeviceStatisticDaily selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_device_daily
     * @mbg.generated  Wed Jan 24 18:30:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") DeviceStatisticDaily record,
            @Param("example") DeviceStatisticDailyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_device_daily
     * @mbg.generated  Wed Jan 24 18:30:45 CST 2018
     */
    int updateByExample(@Param("record") DeviceStatisticDaily record,
            @Param("example") DeviceStatisticDailyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_device_daily
     * @mbg.generated  Wed Jan 24 18:30:45 CST 2018
     */
    int updateByPrimaryKeySelective(DeviceStatisticDaily record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_device_daily
     * @mbg.generated  Wed Jan 24 18:30:45 CST 2018
     */
    @Update({ "update statistic_device_daily", "set statistic_date = #{statisticDate,jdbcType=DATE},",
            "channel_id = #{channelId,jdbcType=BIGINT},", "channel_name = #{channelName,jdbcType=VARCHAR},",
            "app_product_id = #{appProductId,jdbcType=BIGINT},",
            "app_product_name = #{appProductName,jdbcType=VARCHAR},",
            "activate_device_count = #{activateDeviceCount,jdbcType=INTEGER},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP}", "where id = #{id,jdbcType=BIGINT}" })
    int updateByPrimaryKey(DeviceStatisticDaily record);
}