package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.Device;
import com.pinganzhiyuan.model.DeviceExample;
import com.pinganzhiyuan.model.DeviceLog;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface DeviceMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table device
     * @mbg.generated  Thu Dec 28 11:39:36 CST 2017
     */
    long countByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table device
     * @mbg.generated  Thu Dec 28 11:39:36 CST 2017
     */
    int deleteByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table device
     * @mbg.generated  Thu Dec 28 11:39:36 CST 2017
     */
    @Delete({ "delete from device", "where id = #{id,jdbcType=BIGINT}" })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table device
     * @mbg.generated  Thu Dec 28 11:39:36 CST 2017
     */
    @Insert({ "insert into device (device_id, user_id, ", "user_agent, version, ", "channel_id, record_date)",
            "values (#{deviceId,jdbcType=VARCHAR}, #{userId,jdbcType=BIGINT}, ",
            "#{userAgent,jdbcType=VARCHAR}, #{version,jdbcType=INTEGER}, ",
            "#{channelId,jdbcType=BIGINT}, #{recordDate,jdbcType=DATE})" })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table device
     * @mbg.generated  Thu Dec 28 11:39:36 CST 2017
     */
    int insertSelective(Device record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table device
     * @mbg.generated  Thu Dec 28 11:39:36 CST 2017
     */
    List<Device> selectByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table device
     * @mbg.generated  Thu Dec 28 11:39:36 CST 2017
     */
    @Select({ "select", "id, device_id, user_id, user_agent, version, channel_id, record_date", "from device",
            "where id = #{id,jdbcType=BIGINT}" })
    @ResultMap("com.pinganzhiyuan.mapper.DeviceMapper.BaseResultMap")
    Device selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table device
     * @mbg.generated  Thu Dec 28 11:39:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table device
     * @mbg.generated  Thu Dec 28 11:39:36 CST 2017
     */
    int updateByExample(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table device
     * @mbg.generated  Thu Dec 28 11:39:36 CST 2017
     */
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table device
     * @mbg.generated  Thu Dec 28 11:39:36 CST 2017
     */
    @Update({ "update device", "set device_id = #{deviceId,jdbcType=VARCHAR},", "user_id = #{userId,jdbcType=BIGINT},",
            "user_agent = #{userAgent,jdbcType=VARCHAR},", "version = #{version,jdbcType=INTEGER},",
            "channel_id = #{channelId,jdbcType=BIGINT},", "record_date = #{recordDate,jdbcType=DATE}",
            "where id = #{id,jdbcType=BIGINT}" })
    int updateByPrimaryKey(Device record);

    @Select({ "select d.device_id, d.user_id, d.user_agent, d.version, d.channel_id, d.record_date from \n" + 
            "(select * from device_log \n" + 
            "where created_at between date(#{startDate}) and date(#{endDate}) group by device_id\n" + 
            ") as a join device as d on a.device_id = d.device_id" })
    @ResultMap("com.pinganzhiyuan.mapper.DeviceMapper.BaseResultMap")
    List<Device> getExisitDeviceDataList(@Param("startDate") Date startDate, @Param("endDate") Date endDate);
   
}