package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.ProductView;
import com.pinganzhiyuan.model.ProductViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ProductViewMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product_view
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    long countByExample(ProductViewExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product_view
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    int deleteByExample(ProductViewExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product_view
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    @Delete({ "delete from product_view", "where id = #{id,jdbcType=BIGINT}" })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product_view
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    @Insert({ "insert into product_view (statistic_date, app_product_name, ", "product_name, product_uv_count, ",
            "product_pv_count)", "values (#{statisticDate,jdbcType=DATE}, #{appProductName,jdbcType=VARCHAR}, ",
            "#{productName,jdbcType=VARCHAR}, #{productUvCount,jdbcType=INTEGER}, ",
            "#{productPvCount,jdbcType=INTEGER})" })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(ProductView record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product_view
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    int insertSelective(ProductView record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product_view
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    List<ProductView> selectByExample(ProductViewExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product_view
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    @Select({ "select", "id, statistic_date, app_product_name, product_name, product_uv_count, product_pv_count",
            "from product_view", "where id = #{id,jdbcType=BIGINT}" })
    @ResultMap("com.pinganzhiyuan.mapper.ProductViewMapper.BaseResultMap")
    ProductView selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product_view
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductView record, @Param("example") ProductViewExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product_view
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    int updateByExample(@Param("record") ProductView record, @Param("example") ProductViewExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product_view
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    int updateByPrimaryKeySelective(ProductView record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table product_view
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    @Update({ "update product_view", "set statistic_date = #{statisticDate,jdbcType=DATE},",
            "app_product_name = #{appProductName,jdbcType=VARCHAR},", "product_name = #{productName,jdbcType=VARCHAR},",
            "product_uv_count = #{productUvCount,jdbcType=INTEGER},",
            "product_pv_count = #{productPvCount,jdbcType=INTEGER}", "where id = #{id,jdbcType=BIGINT}" })
    int updateByPrimaryKey(ProductView record);
}