package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.Resource;
import com.pinganzhiyuan.model.ResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ResourceMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table resource
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    long countByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table resource
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    int deleteByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table resource
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    @Delete({ "delete from resource", "where id = #{id,jdbcType=BIGINT}" })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table resource
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    @Insert({ "insert into resource (name, type, ", "url, parent_id, parent_ids, ", "permission, is_enabled)",
            "values (#{name,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, ",
            "#{url,jdbcType=VARCHAR}, #{parentId,jdbcType=BIGINT}, #{parentIds,jdbcType=VARCHAR}, ",
            "#{permission,jdbcType=VARCHAR}, #{isEnabled,jdbcType=BIT})" })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table resource
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table resource
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    List<Resource> selectByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table resource
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    @Select({ "select", "id, name, type, url, parent_id, parent_ids, permission, is_enabled", "from resource",
            "where id = #{id,jdbcType=BIGINT}" })
    @ResultMap("com.pinganzhiyuan.mapper.ResourceMapper.BaseResultMap")
    Resource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table resource
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table resource
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    int updateByExample(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table resource
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table resource
     * @mbg.generated  Tue Feb 06 17:28:36 CST 2018
     */
    @Update({ "update resource", "set name = #{name,jdbcType=VARCHAR},", "type = #{type,jdbcType=VARCHAR},",
            "url = #{url,jdbcType=VARCHAR},", "parent_id = #{parentId,jdbcType=BIGINT},",
            "parent_ids = #{parentIds,jdbcType=VARCHAR},", "permission = #{permission,jdbcType=VARCHAR},",
            "is_enabled = #{isEnabled,jdbcType=BIT}", "where id = #{id,jdbcType=BIGINT}" })
    int updateByPrimaryKey(Resource record);
}