package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.Statistic;
import com.pinganzhiyuan.model.StatisticExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface StatisticMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    long countByExample(StatisticExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    int deleteByExample(StatisticExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    @Delete({ "delete from statistic", "where id = #{id,jdbcType=BIGINT}" })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    @Insert({ "insert into statistic (record_date, new_device_count, ", "new_user_count, device_visit_count, ",
            "user_visit_count, product_visit_total_count, ",
            "product_visit_user_total_count, average_product_visit_count)",
            "values (#{recordDate,jdbcType=DATE}, #{newDeviceCount,jdbcType=INTEGER}, ",
            "#{newUserCount,jdbcType=INTEGER}, #{deviceVisitCount,jdbcType=INTEGER}, ",
            "#{userVisitCount,jdbcType=INTEGER}, #{productVisitTotalCount,jdbcType=INTEGER}, ",
            "#{productVisitUserTotalCount,jdbcType=INTEGER}, #{averageProductVisitCount,jdbcType=DECIMAL})" })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(Statistic record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    int insertSelective(Statistic record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    List<Statistic> selectByExample(StatisticExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    @Select({ "select", "id, record_date, new_device_count, new_user_count, device_visit_count, user_visit_count, ",
            "product_visit_total_count, product_visit_user_total_count, average_product_visit_count", "from statistic",
            "where id = #{id,jdbcType=BIGINT}" })
    @ResultMap("com.pinganzhiyuan.mapper.StatisticMapper.BaseResultMap")
    Statistic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") Statistic record, @Param("example") StatisticExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    int updateByExample(@Param("record") Statistic record, @Param("example") StatisticExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    int updateByPrimaryKeySelective(Statistic record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic
     * @mbg.generated  Tue Dec 26 15:59:52 CST 2017
     */
    @Update({ "update statistic", "set record_date = #{recordDate,jdbcType=DATE},",
            "new_device_count = #{newDeviceCount,jdbcType=INTEGER},",
            "new_user_count = #{newUserCount,jdbcType=INTEGER},",
            "device_visit_count = #{deviceVisitCount,jdbcType=INTEGER},",
            "user_visit_count = #{userVisitCount,jdbcType=INTEGER},",
            "product_visit_total_count = #{productVisitTotalCount,jdbcType=INTEGER},",
            "product_visit_user_total_count = #{productVisitUserTotalCount,jdbcType=INTEGER},",
            "average_product_visit_count = #{averageProductVisitCount,jdbcType=DECIMAL}",
            "where id = #{id,jdbcType=BIGINT}" })
    int updateByPrimaryKey(Statistic record);
}