package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.UserPortrayal;
import com.pinganzhiyuan.model.UserPortrayalExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface UserPortrayalMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_user_portrayal
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    long countByExample(UserPortrayalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_user_portrayal
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    int deleteByExample(UserPortrayalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_user_portrayal
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    @Delete({ "delete from statistic_user_portrayal", "where id = #{id,jdbcType=BIGINT}" })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_user_portrayal
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    @Insert({ "insert into statistic_user_portrayal (user_id, cell_phone, ", "regist_time, is_approve, ",
            "approve_time, birth_date, ", "is_man, prefix_of_identity, ", "education, profession, ",
            "guarantee, created_at)", "values (#{userId,jdbcType=BIGINT}, #{cellPhone,jdbcType=VARCHAR}, ",
            "#{registTime,jdbcType=TIMESTAMP}, #{isApprove,jdbcType=BIT}, ",
            "#{approveTime,jdbcType=TIMESTAMP}, #{birthDate,jdbcType=DATE}, ",
            "#{isMan,jdbcType=BIT}, #{prefixOfIdentity,jdbcType=VARCHAR}, ",
            "#{education,jdbcType=VARCHAR}, #{profession,jdbcType=VARCHAR}, ",
            "#{guarantee,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP})" })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(UserPortrayal record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_user_portrayal
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    int insertSelective(UserPortrayal record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_user_portrayal
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    List<UserPortrayal> selectByExample(UserPortrayalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_user_portrayal
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    @Select({ "select", "id, user_id, cell_phone, regist_time, is_approve, approve_time, birth_date, ",
            "is_man, prefix_of_identity, education, profession, guarantee, created_at", "from statistic_user_portrayal",
            "where id = #{id,jdbcType=BIGINT}" })
    @ResultMap("com.pinganzhiyuan.mapper.UserPortrayalMapper.BaseResultMap")
    UserPortrayal selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_user_portrayal
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserPortrayal record, @Param("example") UserPortrayalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_user_portrayal
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    int updateByExample(@Param("record") UserPortrayal record, @Param("example") UserPortrayalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_user_portrayal
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    int updateByPrimaryKeySelective(UserPortrayal record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table statistic_user_portrayal
     * @mbg.generated  Mon Jan 22 15:55:28 CST 2018
     */
    @Update({ "update statistic_user_portrayal", "set user_id = #{userId,jdbcType=BIGINT},",
            "cell_phone = #{cellPhone,jdbcType=VARCHAR},", "regist_time = #{registTime,jdbcType=TIMESTAMP},",
            "is_approve = #{isApprove,jdbcType=BIT},", "approve_time = #{approveTime,jdbcType=TIMESTAMP},",
            "birth_date = #{birthDate,jdbcType=DATE},", "is_man = #{isMan,jdbcType=BIT},",
            "prefix_of_identity = #{prefixOfIdentity,jdbcType=VARCHAR},", "education = #{education,jdbcType=VARCHAR},",
            "profession = #{profession,jdbcType=VARCHAR},", "guarantee = #{guarantee,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP}", "where id = #{id,jdbcType=BIGINT}" })
    int updateByPrimaryKey(UserPortrayal record);
}