package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.Banner;
import com.pinganzhiyuan.model.BannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface BannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    long countByExample(BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    int deleteByExample(BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    @Delete({
        "delete from banner",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    @Insert({
        "insert into banner (credit_ceiling, rate, ",
        "slide_news)",
        "values (#{creditCeiling,jdbcType=INTEGER}, #{rate,jdbcType=INTEGER}, ",
        "#{slideNews,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    int insertSelective(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    List<Banner> selectByExample(BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    @Select({
        "select",
        "id, credit_ceiling, rate, slide_news",
        "from banner",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.pinganzhiyuan.mapper.BannerMapper.BaseResultMap")
    Banner selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") Banner record, @Param("example") BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    int updateByExample(@Param("record") Banner record, @Param("example") BannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    int updateByPrimaryKeySelective(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    @Update({
        "update banner",
        "set credit_ceiling = #{creditCeiling,jdbcType=INTEGER},",
          "rate = #{rate,jdbcType=INTEGER},",
          "slide_news = #{slideNews,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Banner record);
}