package com.pinganzhiyuan.mapper;

import com.pinganzhiyuan.model.Product;
import com.pinganzhiyuan.model.ProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    long countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    @Delete({
        "delete from product",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    @Insert({
        "insert into product (title, subtitle, ",
        "is_published, img_url, ",
        "target_url, weight, ",
        "light_title, floor, ",
        "ceiling, duration_floor, ",
        "duration_ceiling, credit_auth)",
        "values (#{title,jdbcType=VARCHAR}, #{subtitle,jdbcType=VARCHAR}, ",
        "#{isPublished,jdbcType=BIT}, #{imgUrl,jdbcType=VARCHAR}, ",
        "#{targetUrl,jdbcType=VARCHAR}, #{weight,jdbcType=INTEGER}, ",
        "#{lightTitle,jdbcType=VARCHAR}, #{floor,jdbcType=INTEGER}, ",
        "#{ceiling,jdbcType=INTEGER}, #{durationFloor,jdbcType=INTEGER}, ",
        "#{durationCeiling,jdbcType=INTEGER}, #{creditAuth,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    @Select({
        "select",
        "id, title, subtitle, is_published, img_url, target_url, weight, light_title, ",
        "floor, ceiling, duration_floor, duration_ceiling, credit_auth",
        "from product",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.pinganzhiyuan.mapper.ProductMapper.BaseResultMap")
    Product selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    @Update({
        "update product",
        "set title = #{title,jdbcType=VARCHAR},",
          "subtitle = #{subtitle,jdbcType=VARCHAR},",
          "is_published = #{isPublished,jdbcType=BIT},",
          "img_url = #{imgUrl,jdbcType=VARCHAR},",
          "target_url = #{targetUrl,jdbcType=VARCHAR},",
          "weight = #{weight,jdbcType=INTEGER},",
          "light_title = #{lightTitle,jdbcType=VARCHAR},",
          "floor = #{floor,jdbcType=INTEGER},",
          "ceiling = #{ceiling,jdbcType=INTEGER},",
          "duration_floor = #{durationFloor,jdbcType=INTEGER},",
          "duration_ceiling = #{durationCeiling,jdbcType=INTEGER},",
          "credit_auth = #{creditAuth,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Product record);
}