package com.pinganzhiyuan.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.title
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.subtitle
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_published
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    private Boolean isPublished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.img_url
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.target_url
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    private String targetUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.weight
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.light_title
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    private String lightTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.floor
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    private Integer floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ceiling
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    private Integer ceiling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.duration_floor
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    private Integer durationFloor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.duration_ceiling
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    private Integer durationCeiling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.credit_auth
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    private String creditAuth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.title
     *
     * @return the value of product.title
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.title
     *
     * @param title the value for product.title
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.subtitle
     *
     * @return the value of product.subtitle
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.subtitle
     *
     * @param subtitle the value for product.subtitle
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_published
     *
     * @return the value of product.is_published
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public Boolean getIsPublished() {
        return isPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_published
     *
     * @param isPublished the value for product.is_published
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public void setIsPublished(Boolean isPublished) {
        this.isPublished = isPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.img_url
     *
     * @return the value of product.img_url
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.img_url
     *
     * @param imgUrl the value for product.img_url
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.target_url
     *
     * @return the value of product.target_url
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public String getTargetUrl() {
        return targetUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.target_url
     *
     * @param targetUrl the value for product.target_url
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public void setTargetUrl(String targetUrl) {
        this.targetUrl = targetUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.weight
     *
     * @return the value of product.weight
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.weight
     *
     * @param weight the value for product.weight
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.light_title
     *
     * @return the value of product.light_title
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public String getLightTitle() {
        return lightTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.light_title
     *
     * @param lightTitle the value for product.light_title
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public void setLightTitle(String lightTitle) {
        this.lightTitle = lightTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.floor
     *
     * @return the value of product.floor
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.floor
     *
     * @param floor the value for product.floor
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ceiling
     *
     * @return the value of product.ceiling
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public Integer getCeiling() {
        return ceiling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ceiling
     *
     * @param ceiling the value for product.ceiling
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public void setCeiling(Integer ceiling) {
        this.ceiling = ceiling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.duration_floor
     *
     * @return the value of product.duration_floor
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public Integer getDurationFloor() {
        return durationFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.duration_floor
     *
     * @param durationFloor the value for product.duration_floor
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public void setDurationFloor(Integer durationFloor) {
        this.durationFloor = durationFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.duration_ceiling
     *
     * @return the value of product.duration_ceiling
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public Integer getDurationCeiling() {
        return durationCeiling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.duration_ceiling
     *
     * @param durationCeiling the value for product.duration_ceiling
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public void setDurationCeiling(Integer durationCeiling) {
        this.durationCeiling = durationCeiling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.credit_auth
     *
     * @return the value of product.credit_auth
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public String getCreditAuth() {
        return creditAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.credit_auth
     *
     * @param creditAuth the value for product.credit_auth
     *
     * @mbg.generated Fri Dec 08 11:34:49 CST 2017
     */
    public void setCreditAuth(String creditAuth) {
        this.creditAuth = creditAuth;
    }
}