package com.pinganzhiyuan.dto;

import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.pinganzhiyuan.model.Product;

public class ProductDTO {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.title
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.is_new
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Boolean isNew;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.first_tags
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private List<String> firstTags;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.second_tags
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private String secondTags;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.description
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private String description;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.is_published
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Integer isPublished;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.img_url
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private String imgUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.url
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.weight
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Integer weight;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.light_title
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private String lightTitle;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.min_amount
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Integer minAmount;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.max_amount
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Integer maxAmount;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.min_term
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Integer minTerm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.max_term
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Integer maxTerm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.low_interest
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Double lowInterest;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.high_interest
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Double highInterest;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.lender_name
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private String lenderName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.lender_desc
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private String lenderDesc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.active_captcha_url
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private String activeCaptchaUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.reg_interface_url
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private String regInterfaceUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.publish_time
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Date publishTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.unpublish_time
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Date unpublishTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.apply_times
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Integer applyTimes;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.loan_wait_time
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    private Integer loanWaitTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.id
     * @return  the value of product.id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.id
     * @param id  the value for product.id
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.title
     * @return  the value of product.title
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.title
     * @param title  the value for product.title
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.is_new
     * @return  the value of product.is_new
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Boolean getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.is_new
     * @param isNew  the value for product.is_new
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.first_tags
     * @return  the value of product.first_tags
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public List<String> getFirstTags() {
        return firstTags;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.first_tags
     * @param firstTags  the value for product.first_tags
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setFirstTags(List<String> firstTags) {
        this.firstTags = firstTags;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.second_tags
     * @return  the value of product.second_tags
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public String getSecondTags() {
        return secondTags;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.second_tags
     * @param secondTags  the value for product.second_tags
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setSecondTags(String secondTags) {
        this.secondTags = secondTags;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.description
     * @return  the value of product.description
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.description
     * @param description  the value for product.description
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getIsPublished() {
        return isPublished;
    }

    public void setIsPublished(Integer isPublished) {
        this.isPublished = isPublished;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.img_url
     * @return  the value of product.img_url
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.img_url
     * @param imgUrl  the value for product.img_url
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.url
     * @return  the value of product.url
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.url
     * @param url  the value for product.url
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.weight
     * @return  the value of product.weight
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.weight
     * @param weight  the value for product.weight
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.light_title
     * @return  the value of product.light_title
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public String getLightTitle() {
        return lightTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.light_title
     * @param lightTitle  the value for product.light_title
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setLightTitle(String lightTitle) {
        this.lightTitle = lightTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.min_amount
     * @return  the value of product.min_amount
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Integer getMinAmount() {
        return minAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.min_amount
     * @param minAmount  the value for product.min_amount
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setMinAmount(Integer minAmount) {
        this.minAmount = minAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.max_amount
     * @return  the value of product.max_amount
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Integer getMaxAmount() {
        return maxAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.max_amount
     * @param maxAmount  the value for product.max_amount
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setMaxAmount(Integer maxAmount) {
        this.maxAmount = maxAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.min_term
     * @return  the value of product.min_term
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Integer getMinTerm() {
        return minTerm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.min_term
     * @param minTerm  the value for product.min_term
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setMinTerm(Integer minTerm) {
        this.minTerm = minTerm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.max_term
     * @return  the value of product.max_term
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Integer getMaxTerm() {
        return maxTerm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.max_term
     * @param maxTerm  the value for product.max_term
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setMaxTerm(Integer maxTerm) {
        this.maxTerm = maxTerm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.low_interest
     * @return  the value of product.low_interest
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Double getLowInterest() {
        return lowInterest;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.low_interest
     * @param lowInterest  the value for product.low_interest
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setLowInterest(Double lowInterest) {
        this.lowInterest = lowInterest;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.high_interest
     * @return  the value of product.high_interest
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Double getHighInterest() {
        return highInterest;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.high_interest
     * @param highInterest  the value for product.high_interest
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setHighInterest(Double highInterest) {
        this.highInterest = highInterest;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.lender_name
     * @return  the value of product.lender_name
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public String getLenderName() {
        return lenderName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.lender_name
     * @param lenderName  the value for product.lender_name
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setLenderName(String lenderName) {
        this.lenderName = lenderName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.lender_desc
     * @return  the value of product.lender_desc
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public String getLenderDesc() {
        return lenderDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.lender_desc
     * @param lenderDesc  the value for product.lender_desc
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setLenderDesc(String lenderDesc) {
        this.lenderDesc = lenderDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.active_captcha_url
     * @return  the value of product.active_captcha_url
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public String getActiveCaptchaUrl() {
        return activeCaptchaUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.active_captcha_url
     * @param activeCaptchaUrl  the value for product.active_captcha_url
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setActiveCaptchaUrl(String activeCaptchaUrl) {
        this.activeCaptchaUrl = activeCaptchaUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.reg_interface_url
     * @return  the value of product.reg_interface_url
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public String getRegInterfaceUrl() {
        return regInterfaceUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.reg_interface_url
     * @param regInterfaceUrl  the value for product.reg_interface_url
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setRegInterfaceUrl(String regInterfaceUrl) {
        this.regInterfaceUrl = regInterfaceUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.publish_time
     * @return  the value of product.publish_time
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.publish_time
     * @param publishTime  the value for product.publish_time
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.unpublish_time
     * @return  the value of product.unpublish_time
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Date getUnpublishTime() {
        return unpublishTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.unpublish_time
     * @param unpublishTime  the value for product.unpublish_time
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setUnpublishTime(Date unpublishTime) {
        this.unpublishTime = unpublishTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.apply_times
     * @return  the value of product.apply_times
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Integer getApplyTimes() {
        return applyTimes;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.apply_times
     * @param applyTimes  the value for product.apply_times
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setApplyTimes(Integer applyTimes) {
        this.applyTimes = applyTimes;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.loan_wait_time
     * @return  the value of product.loan_wait_time
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public Integer getLoanWaitTime() {
        return loanWaitTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.loan_wait_time
     * @param loanWaitTime  the value for product.loan_wait_time
     * @mbg.generated  Tue Jan 23 10:34:09 CST 2018
     */
    public void setLoanWaitTime(Integer loanWaitTime) {
        this.loanWaitTime = loanWaitTime;
    }
    
    private List<String> guarantees;

    public List<String> getGuarantees() {
        return guarantees;
    }

    public void setGuarantees(List<String> guarantees) {
        this.guarantees = guarantees;
    }

    private String dayRate;
    
    public String getDayRate() {
        return dayRate;
    }

    public void setDayRate(String dayRate) {
        this.dayRate = dayRate;
    }
    
    private String originUrl;

    public String getOriginUrl() {
        return originUrl;
    }

    public void setOriginUrl(String originUrl) {
        this.originUrl = originUrl;
    }

    public ProductDTO(Product product) {
        this.id = product.getId();
        this.title = product.getTitle();
        this.isNew = product.getIsNew();
        
        // 标签需要转成数组类型
        this.firstTags = new ArrayList<>();
        String tags = product.getFirstTags();
        String[] split = tags.split("\\|");
        for (String tag : split) {
            this.firstTags.add(tag);
        }
        
        String secondTags2 = product.getSecondTags();
        if (secondTags2 != null) {
            Pattern p = Pattern.compile("日利率(.*?)\\%起");
            Matcher m = p.matcher(secondTags2);
            if (m.find()) {
//                System.out.println(m.group(1));
                this.dayRate = m.group(1);
            }
        }
//        this.firstTags = product.getFirstTags();
//        this.secondTags = product.getSecondTags();
        this.description = product.getDescription();
        this.isPublished = product.getIsPublished();
        this.imgUrl = product.getImgUrl();
        
        this.url = product.getUrl();
        // 根据 url 返回
//        redirect=
        // 处理 URL，截取最后真正的链接
//        for (Product product : productList) {
            String decodeUrl = "";
            Pattern p = Pattern.compile("redirect=(.*?)###");//正则表达式，取; 和; 之间的字符串  
            Matcher m = p.matcher(product.getUrl() + "###");
            if (m.find()) {
                    try {
                        decodeUrl = URLDecoder.decode(m.group(1), "UTF-8");
                } catch (UnsupportedEncodingException e) {
                    e.printStackTrace();
                }
            }
//            product.setUrl(decodeUrl);
//        }
        this.originUrl = decodeUrl;
        
        this.weight = product.getWeight();
        this.lightTitle = product.getLightTitle();
        this.minAmount = product.getMinAmount();
        this.maxAmount = product.getMaxAmount();
        this.minTerm = product.getMinTerm();
        this.maxTerm = product.getMaxTerm();
        this.lowInterest = product.getLowInterest();
        this.highInterest = product.getHighInterest();
        this.lenderName = product.getLenderName();
        this.lenderDesc = product.getLenderDesc();
        this.activeCaptchaUrl = product.getActiveCaptchaUrl();
        this.regInterfaceUrl = product.getRegInterfaceUrl();
        this.publishTime = product.getPublishTime();
        this.unpublishTime = product.getUnpublishTime();
        this.applyTimes = product.getApplyTimes();
        this.loanWaitTime = product.getLoanWaitTime();
        
        this.guarantees = new ArrayList<>();
    }
}
